AcademySoftwareFoundation/OpenTimelineIO

README.md

Looks like this (though it'll show as _passing_ after the master branch is built):

CI build status in README

---

opentimelineio/opentime.py
tests/test_cdl.py
tests/test_cmx_3600_adapter.py
tests/test_opentime.py

Attempting to address #156 and #155

Time fixes

---

contrib/adapters/ale.py
contrib/adapters/tests/test_ale_adapter.py

ALE "Source File" now round-trips to each Clip's media_reference.target_url.
ALE export now gracefully handles items with no source_range.

Small ALE improvements

---

opentimelineio/adapters/cmx_3600.py
tests/test_cmx_3600_adapter.py

Should address https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/103.

Support EDL dissolve writes

---

opentimelineio/adapters/cmx_3600.py
tests/test_cmx_3600_adapter.py

Replaces https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/203.

Support for fades.

---

.travis.yml
contrib/adapters/advanced_authoring_format.py
contrib/adapters/tests/test_aaf_adapter.py

Folding @mikemahony 's work on our Travis setup such that PyAAF gets installed. This ensures that the new AAF adapter gets tested properly.

Add PyAAF to Travis CI

---

opentimelineview/timeline_widget.py

Fixed a bug in otioview that broke with some of our sample test files.

---

bin/otioview.py
opentimelineio/adapters/cmx_3600.py

haven't tested this w/ pyside, just a proposal

Pass adapter arguments into otioview.

---

opentimelineio/schema/gap.py
tests/baselines/empty_gap.json
tests/test_item.py

Add convienence constructor for Gap

---

opentimelineview/timeline_widget.py

Keyboard shortcuts for OTIOview

---

opentimelineio_contrib/adapters/advanced_authoring_format.py

AAF container was pruning compositions that had only one child regardless of the type of the child.

Better pruning of extra containers.

---

opentimelineio_contrib/adapters/advanced_authoring_format.py

Co-authored-by: Freeson Wang <freeson@pixar.com>

Adding Transition PointList metadata for creating AAF Transition objects

---

setup.py

add aaf_adapter module to setuppy

---

contrib/opentimelineio_contrib/adapters/aaf_adapter/aaf_writer.py
contrib/opentimelineio_contrib/adapters/advanced_authoring_format.py
contrib/opentimelineio_contrib/adapters/tests/test_aaf_adapter.py
contrib/opentimelineio_contrib/adapters/tests/test_rvsession.py

Ideally this gets contrib area tests passing for the CXX branch.  We shouldn't need to cherry pick this change to master.

Python3 contrib area unit test cleanups.

---

src/opentimelineio/deserialization.cpp
src/opentimelineio/serializableObject.h

We want the position in the file for invalid json, missing fields, etc.  With this change, json parse errors are reported exactly where they occur.  Most other errors are reported with a line number that is the last line of the innermost schema object in which the error occurred.

add line numbers to error strings

---

tests/test_console.py

Adds some code that runs the console unit tests directly through the shell as well as through the function calls.

Run console test

---

setup.py
src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py

Bumping beta version in Cxx branch to match master

---

src/py-opentimelineio/opentimelineio/schema/schemadef.py

Added __str__and __repr__ to SchemaDef to match other classes.

Added repr for SchemaDefs

---

.gitignore

Ignore xcode and vscode user data

---

src/py-opentimelineio/opentimelineio/plugins/manifest.py

Fixes #581 
I clobbered the changes from PR #582 in PR #591. This reinstates the fix.

Issue-581 - Clobbered by PR #591

---

contrib/opentimelineio_contrib/adapters/extern_rv.py
contrib/opentimelineio_contrib/adapters/tests/sample_data/image_sequence_example.otio
contrib/opentimelineio_contrib/adapters/tests/test_rvsession.py

Quick implementation of `ImageSequenceReference` in the `extern_rv.py` adapter to get the ball rolling :)
Added a sample file and test for it as well.

[WIP] Implement ImageSequenceReference in extern_rv 

---

docs/index.rst

As we prep for the ASWF transition, these presentations will move out of the repo and elsewhere.

Closes #652 Remove presentations from repo.

---

contrib/opentimelineio_contrib/adapters/tests/tests_xges_adapter.py
contrib/opentimelineio_contrib/adapters/xges.py

Fixes https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/657

Updating Copyright notices

---

src/CMakeLists.txt

Adds some checks to make sure that git is present before attempting to recursively update.

Tweaks to cmake so that pip and local builds both work

---

src/c-opentimelineio/opentimelineio-bindings/CMakeLists.txt
src/c-opentimelineio/opentimelineio-bindings/include/copentimelineio/any.h
src/c-opentimelineio/opentimelineio-bindings/include/copentimelineio/anyDictionary.h
src/c-opentimelineio/opentimelineio-bindings/include/copentimelineio/safely_typed_any.h
src/c-opentimelineio/opentimelineio-bindings/src/any.cpp
src/c-opentimelineio/opentimelineio-bindings/src/anyDictionary.cpp
src/c-opentimelineio/opentimelineio-bindings/src/composableRetainerVector.cpp
src/c-opentimelineio/opentimelineio-bindings/src/composableVector.cpp
src/c-opentimelineio/opentimelineio-bindings/src/effectRetainerVector.cpp
src/c-opentimelineio/opentimelineio-bindings/src/effectVector.cpp
src/c-opentimelineio/opentimelineio-bindings/src/item.cpp
src/c-opentimelineio/opentimelineio-bindings/src/markerRetainerVector.cpp
src/c-opentimelineio/opentimelineio-bindings/src/markerVector.cpp
src/c-opentimelineio/opentimelineio-bindings/src/safely_typed_any.cpp
src/c-opentimelineio/opentimelineio-bindings/src/serializableObjectRetainerVector.cpp
src/c-opentimelineio/opentimelineio-bindings/src/serializableObjectVector.cpp
src/c-opentimelineio/opentimelineio-bindings/src/trackVector.cpp
src/c-opentimelineio/tests/openTimeTests.cpp
src/c-opentimelineio/tests/openTimelineIOTests.cpp

Wrapped `safely_typed_any.h`
Next, I'll push a few return fixes, and will move on to tests.

C bindings - wrap safely typed any

---

src/opentime/rationalTime.h

Each PR should link at least one issue, in the form:
Fixes #573 
Use one line for each Issue. This allows auto-closing the related issue when the fix is merged.
To check that rate and value are not invalid.
Add a list of changes, and note any that might need special attention during review.
If no new tests are introduced as part of this PR, note the tests that are providing coverage.

Check rate and value are not invalid

---

tests/test_image_sequence_reference.py

We haven't updated pybind11 in quite some time.  This branch was created to see if some of the issues with nice function signatures @reinecke was seeing were addressed by newer versions of pybind11.

bump pybind11 up to latest release

---

docs/cxx/cxx.rst
docs/tutorials/architecture.md
docs/tutorials/contributing.md
docs/tutorials/otio-timeline-structure.md
docs/tutorials/time-ranges.md
docs/tutorials/write-a-hookscript.md
docs/tutorials/write-a-media-linker.md
docs/tutorials/write-a-schemadef.md
docs/tutorials/write-an-adapter.md

```Fixes #913```
First of all thanks for all the nice documentation! I was just reading through it and noticed a couple of minor typos and small changes that could make the formatting more consistent. This PR has my suggested changes.

Documentation fixes

---

.github/dependabot.yml

- add dependabot support for versioning GitHub actions

uncomment github actions dependabot config

---

CMakeLists.txt

Upgrade to C++14

---

Makefile

Fix Makefile format: target

---

README.md
docs/tutorials/contributing.md

- adds notes to README.md and the contributing doc file about what our policy is, as well as links to the VFX platform homepage explaining it.

Add information on VFX platform support to repo

---

contrib/opentimelineio_contrib/application_plugins/tests/test_rv_reader.py

Fixes #1148
There are a few Mac OS-specific fixes here:
- The RV_BIN_DIR is expected to be named 'bin'.  This is not the case on Mac where RV is packaged as a Mac application and the binaries relative to the install root are in `RV.app/Contents/MacOS/`.  This is fixed by checking for Mac and changing `bin` for `MacOS` if it's the case.
- The package installation tries to verify the package was installed correctly by matching the installation path to the list of RV packages.  This fails because the test installs in Mac's tempdir (`/var/tmp`) which is actually a symlink to `/private/var/tmp`, and RV displays the path with the symlink resolved.  Fix this by using `realpath` to resolve the symlinks prior to the installation so the paths match.
- On Mac the …

Fix RV plugin test for Mac

---

setup.py

Setting version for future patch release of v0.14

Bumped version to 0.14.1.dev1

---

contrib/opentimelineio_contrib/adapters/tests/sample_data/not_aaf.otio

This commit was accidentally left out of #932

More ASWF transition prep

---

docs/style-guide.md

Starting a PR to revise the style-guide in order to be able to take advantage of the suggest tag and other code review tools here on github.

Style Guide

---

src/opentimelineview/timeline_widget.py

Addressing issue: https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/1261

Adapt changes between PySide2 and PySide6

---

contrib/opentimelineio_contrib/adapters/extern_rv.py
contrib/opentimelineio_contrib/adapters/hls_playlist.py
contrib/opentimelineio_contrib/adapters/tests/test_hls_playlist_adapter.py
tests/test_fcp7_xml_adapter.py
tests/test_plugin_detection.py

Fixes #1369 .
Simply fixing lint issues that recently appeared due to a flake8 update.

Fix lint issues

---

src/opentime/rationalTime.h

Should solve CI issues with PR #1644 
(cherry picked from commit d1e78073d4fc321b667ceffc2d95251015af5fea)
Signed-off-by: Jean-Christophe Morin <jean_christophe_morin@hotmail.com>

Cherry picked commit to unblock PR #1644

---

ADOPTERS.md
MANIFEST.in
docs/conf.py

Adds an ADOPTERS file which brings the project closer to meeting the ASWF [Adopted requirements](https://tac.aswf.io/process/lifecycle.html#requirements-2).

Added a list of applications integrating OTIO

---

README.md

This PR includes a couple of small changes to simplify the C++ example code in the README.

Simplify the C++ example

---

ADOPTERS.md

Added Kdenlive and organized list by alphabetical order.

Add Kdenlive
