AcademySoftwareFoundation/OpenTimelineIO

tests/test_adapter_plugin.py
tests/test_builtin_adapters.py
tests/test_media_linker.py
tests/utils.py

The tests were running on `*nix` only, so I moved all of the test manifest creation to happen in a temp directory and clean up the file when finished.

Make tests cross platform

---

opentimelineio/core/composition.py
opentimelineio/core/item.py
opentimelineio/core/type_registry.py
tests/test_composition.py

This PR:
- Fixes a bug where deserialized OTIO objects were missing their correct `._parent` pointers.
- Adds the `trimmed_range_in_parent` convenience method.  This method wraps up the pattern: `some_item.parent().trimmed_range_of_child(some_item)`.

Add trimmed_range_in_parent method to core.Item

---

opentimelineview/timeline_widget.py

- Add support for nested sequences to `opentimelineview` library (prior version supported nested Stacks but not nested Sequences).
- this is done by adding support for `otio.schema.Sequence` to the `StackView`
- Fix small bugs associated with using `source_range` directly instead of going through the `trimmed_range` wrapper
- Renames `Track` widget class to `TrackWidget` to disambiguate it

Add nested sequence support to OTIOView

---

.travis.yml
LICENSE.txt
contrib/adapters/burnins.py
contrib/adapters/contrib_adapters.plugin_manifest.json
contrib/adapters/ffmpeg_burnins.py
contrib/adapters/tests/test_burnins.py

Removed enums.
Constants are now global (as opposed to a class namespace).
Updating the MIT license with preamble.

Burnin adapter (second attempt)

---

bin/otiostat.py

This PR adds the `bin/otiostat.py` program, which prints various information about `.otio` files out and can be used to validate `.otio` files.

Otiostat program: validate and print information about your .otio file.

---

contrib/adapters/tests/test_burnins.py

Noticed that tests fail instead of skip if PIL isn't installed, so added a check for it.  Now unit tests skip instead of fail if PIL isn't installed for the contrib/burnin adapter.

Add check to see if PIL is importable before running tests.

---

opentimelineio/adapters/__init__.py
opentimelineio/adapters/adapter.py
tests/baselines/example.py
tests/test_adapter_plugin.py

In order for adapters to have custom extra arguments (for example a `rate` argument for the EDL adapter), the adapter plugin system will now pass keyword arguments along to the adapters.

Adapter argument map

---

opentimelineio/opentime.py
tests/test_opentime.py

New pull request for timestring formatting for FFmpeg.
Functions done by calling opentime.to_seconds to increase consistency.
It kinda works, even if some unit test doesn't works due to precision, that may be handle by the todo put in value_rescaled_to() function.

Time string functions

---

opentimelineio/adapters/cmx_3600.py
tests/sample_data/nucoda_example.edl
tests/test_cmx_3600_adapter.py

Nucoda EDLs use a `* FROM FILE:` comment string to reference media in place of `* FROM CLIP:`.  This change introduces Nucoda EDL writing using an EDL `style` argument, and also supports Nucoda EDL reads.

Add support for Nucoda EDLs

---

opentimelineio/adapters/fcp_xml.py
opentimelineview/timeline_widget.py
tests/sample_data/premiere_example.xml

addresses #174 
- uses clip item rate instead of source rate
- edited clipitem in premiere_example.xml that has different rate compared to its linked file
- fixed bug in timeline_widget, transitions don`t have trimmed_range_in_parent method
- fixed bug in timeline_widget, left over rename from stack to composition

FCP adapter uses clip item rate instead of source rate

---

opentimelineio/adapters/adapter.py
opentimelineio/algorithms/track_algo.py
opentimelineio/core/composable.py
opentimelineio/core/item.py
opentimelineio/media_reference.py
opentimelineio/schema/effect.py
opentimelineio/schema/marker.py
opentimelineio/schema/timeline.py
tests/test_adapter_plugin.py
tests/test_composition.py
tests/test_media_linker.py
tests/utils.py

Fixed a bug that caused problems if you tried to add an item to a Composition twice.
Minor cleanup of some imports that caused problems when running tests via PyCharm.
Minor cleanup of some property initialization.
This addresses #194

Parenting bug fix + small cleanup

---

opentimelineio/schema/timeline.py
tests/test_composition.py

The top level Timeline class's each_child method defaulted to finding only Compositions, but it should find all Composables.
Added unit tests for the recursion behaviour of each_child.

Fixed a bug in Timeline's each_child

---

.gitignore
contrib/adapters/ale.py
contrib/adapters/extern_maya_sequencer.py
contrib/adapters/extern_rv.py
contrib/adapters/hls_playlist.py
contrib/adapters/tests/test_hls_playlist_adapter.py
examples/conform.py
examples/shot_detect.py
opentimelineio/__init__.py
opentimelineio/adapters/cmx_3600.py
opentimelineio/adapters/fcp_xml.py
opentimelineio/core/__init__.py
opentimelineio/core/media_reference.py
opentimelineio/media_linker.py
opentimelineio/schema/__init__.py
opentimelineio/schema/clip.py
opentimelineio/schema/external_reference.py
opentimelineio/schema/missing_reference.py
tests/baselines/example.py
tests/test_cdl.py
tests/test_clip.py
tests/test_cmx_3600_adapter.py
tests/test_composition.py
tests/test_fcp7_xml_adapter.py
tests/test_json_backend.py
tests/test_media_linker.py
tests/test_media_reference.py
tests/test_sequence_algo.py
tests/test_serializable_collection.py
tests/test_timeline.py

This is to clear room to make `GeneratorReference` a child class of `MediaReference`.
- Move `otio.media_reference` -> `otio.core.media_reference`
- Rename `media_reference.External` to `schema.ExternalReference`
- Move `MissingReference` into Schema.

Refactor media reference

---

opentimelineio/adapters/cmx_3600.py
tests/test_cmx_3600_adapter.py

We've observed that EDLs with frame numbers, as opposed to timecode, are valid.  For example:
```
1 CLPA V C     113 170 0  57
2 CLPA V C     170 170 57 57
2 CLPB V D 027 162 189 57 84
3 CLPB V C     189 381 84 276
```

Frame numbers (not just timecode) are ok

---

opentimelineio/adapters/cmx_3600.py
tests/test_cmx_3600_adapter.py

`Gap`s were incorrectly being written as EDL events.  This will produce an actual gap in the record timecode.

Correctly represent Gaps

---

opentimelineio/algorithms/__init__.py
opentimelineio/algorithms/filter.py
tests/test_filter_algorithms.py

Adds functions for filtering OTIO files:
- `otio.algorithms.filtered_items(<input otio object>, <unary function>)` - if the unary function returns an object, that object is placed into the hierarchy.  If it returns none, it is pruned.  Note that if you delete children, it will still visit them.
- `otio.algorithms.filtered_items_sequence_context(<input otio object>, <ternary function>)` ternary function that takes (prev, child, next) for items in tracks.  Otherwise will get passed (None, child, None).  behaves like above.
- both functions have arguments `types_to_prune` and `types_to_filter`.  
- If `types_to_prune` is not `None`, each item that is derived from a type in the `types_to_prune` list will be pruned from the result (the function will not be called on it)
- if `types_to_filter` …

Add functions for filtering OTIO hierarchies.

---

opentimelineio/adapters/cmx_3600.py
opentimelineio/core/composition.py
opentimelineio/exceptions.py
opentimelineio/schema/track.py
tests/test_composition.py

If you have duplicate Clips in a Track (identical, but not instances of the same object) then range_of_child() and other methods don't work as expected. This is because we were using index() to find objects in a Composition, but index() uses the `==` operator instead of `is`.
This PR introduces index_of_child() and fixes a range_of_child() and other related methods to work properly when duplicate clips are present.
Addresses #222

Fix iteration of dupes

---

opentimelineio/opentime.py
tests/test_opentime.py

If no rate is provided then use the rate of the of the given opentime
object.

opentime.py.to_timecode: Use given opentime object's rate for default

---

.gitignore
setup.cfg
setup.py

This PR does some groundwork to make #239 (Put OTIO on PyPi)  possible:
* Add a `setup.cfg` file which points to the `README.md` file for the description
* Update `setup.py` with:
* Classifiers
* License
* Keywords
* `install_requires` placeholder
* support for running the main test suite with `python setup.py test`
In addition, it includes a commit to add the Pycharm `.idea/` folder to `.gitignore`. This commit can be removed from the PR if desired.

PyPi updates (#239)

---

bin/otioview.py

This is for a cleaner user experience.
Helps address #245

Use the 'append' form instead of nargs=+ form to support multiple arguments

---

bin/otioview.py
opentimelineview/details_widget.py

Moved the details widget to the right side.
Added syntax highlighting to the OTIO details.
Switched to a different style (still not great).
Window is bigger and centered.
Fixed the File->Open... menu item.

otioview UI improvements

---

.travis.yml
Makefile
opentimelineio_contrib/adapters/Makefile

Originally, `make test` didn't run `make test-contrib` - but now it does!  So we don't need to run it twice on travis.  Will make travis CI run slightly faster (2s or so).

Make test runs test-contrib, so these don't need to be run twice.

---

bin/otioview.py

You can pass True, False, etc. as real values, instead of everything coming in as a string.

otioview's --adapter_arg can now handle Python literals, 

---

opentimelineio/adapters/cmx_3600.py
opentimelineio/adapters/fcp_xml.py
opentimelineio/algorithms/filter.py
opentimelineio/core/composition.py
opentimelineio/core/media_reference.py
opentimelineio/core/serializable_object.py
opentimelineio/schema/external_reference.py
opentimelineio/schema/marker.py
opentimelineio/schema/track.py
opentimelineio/test_utils.py
tests/test_adapter_plugin.py
tests/test_builtin_adapters.py
tests/test_clip.py
tests/test_cmx_3600_adapter.py
tests/test_composable.py
tests/test_composition.py
tests/test_effect.py
tests/test_fcp7_xml_adapter.py
tests/test_filter_algorithms.py
tests/test_generator_reference.py
tests/test_item.py
tests/test_json_backend.py
tests/test_marker.py
tests/test_media_reference.py
tests/test_serializable_collection.py
tests/test_serializable_object.py
tests/test_stack_algo.py
tests/test_timeline.py
tests/test_track_algo.py
tests/test_transition.py

Changes the equality of `SerializableObject` to use `id()` (`is` style equality) instead of the contents of the `.data` dictionary.  This clarifies that OTIO `SerializableObjects` are 'reference type' objects rather than 'value type' objects.
- removes implementation of `__hash__` and `__eq__` on `SerializableObject`
- adds cbb implementation of `is_equivalent_to` on `SerializableObject`
- adds explicit instance insertion prevention in `Composition`
- removes `index_of_child` and replaces with calls to `index`
- adds the `test_utils` module, which has assertions that use the `is_equivalent_to` method instead of equality, and a handy method that compares json output (which is much more readable)

Reference type implementation

---

.codecov.yml
.travis.yml
README.md
codecov.yml

Closes #192 
Process:
1 ) Connect the PixarAnimationStudios Github account to codecov.io (ignore the token stuff on the Overview page after you sign in, it's not necessary since OTIO is OSS)
2 ) Select the OpenTimelineIO repository - you can see the reports after I connected it [here](https://codecov.io/gh/alexwidener/OpenTimelineIO/commits)
3 ) Run a build for Travis, which causes a coverage report to get kicked off which updates the badge (for the master branch).
4) [There's a Github integration for Codecov if you want to check it out](https://github.com/integration/codecov)
Final result:
Additionally, check out the cool graphs: https://docs.codecov.io/docs/graphs#section-sunburst
Sorry for a bunch of dumb commits, I was just testing stuff - you can squash the commits into one commit …

192 code coverage badge

---

setup.py

Sets the `zip_safe = False` because we use open() to fetch files from OTIO - which means OTIO can't be used with compressed eggs.

Add zip_safe = false flag to address #270.

---

Makefile
README.md
setup.py

This does _not_ add PySide2 or PySide1, but it does add the dependencies for flake8 and coverage, as well as documentation for how to install the dependencies to the README.
PySide2 Snapshot wheels are available through the following: 
`pip install --index-url=http://download.qt.io/snapshots/ci/pyside/5.9/latest/ pyside2 --trusted-host download.qt.io` 
and are hosted at http://download.qt.io/snapshots/ci/pyside/5.9/latest/pyside2/
Since you may be about to merge in #160 I chose not to add PySide2 for 2 reasons. 
1 ) To not get out of date immediately :)
2 ) The above are _snapshots_ and therefore not versioned. I think until PySide2 enters into versioned tagging, it should be up to the person managing the distribution of OTIO in their facility to handle which PySide2 version they have …

Add development requirements to package and instructions to README

---

setup.py

```
(venv) ~/dev/OpenTimelineIO  (pyside2-updates)
└─ ▶ otioconvert
usage: otioconvert [-h] -i INPUT -o OUTPUT [-I INPUT_ADAPTER]
[-O OUTPUT_ADAPTER] [-T TRACKS] [-m MEDIA_LINKER]
otioconvert: error: the following arguments are required: -i/--input, -o/--output
```
```
(venv) ~/dev/OpenTimelineIO  (pyside2-updates)
└─ ▶ otiocat
usage: otiocat [-h] filepath [filepath ...]
otiocat: error: the following arguments are required: filepath
```
```
(venv) ~/dev/OpenTimelineIO  (pyside2-updates)
└─ ▶ otioview tests/sample_data/clip_example.otio
```

Add console entry points for application

---

opentimelineio_contrib/adapters/tests/sample_data/screening_example.rv

RV baseline needed to be updated, had a bunch of `.0`s.

Fix rv baseline

---

examples/sample_plugin/otio_counter/__init__.py
examples/sample_plugin/otio_counter/adapter.py
examples/sample_plugin/otio_counter/plugin_manifest.json
examples/sample_plugin/setup.py
opentimelineio/plugins/manifest.py
setup.py
tests/baseline_reader.py
tests/baselines/plugin_module/otio_jsonplugin.egg-info/PKG-INFO
tests/baselines/plugin_module/otio_jsonplugin.egg-info/entry_points.txt
tests/baselines/plugin_module/otio_jsonplugin/plugin_manifest.json
tests/baselines/plugin_module/otio_mockplugin.egg-info/PKG-INFO
tests/baselines/plugin_module/otio_mockplugin.egg-info/entry_points.txt
tests/baselines/plugin_module/otio_mockplugin/__init__.py
tests/baselines/plugin_module/otio_mockplugin/plugin_manifest.json
tests/test_plugin_detection.py

Submit for discussion, an approach to allow for plugin modules to be registered using setuptools entry points.
If the approach looks reasonable, I can do a pass to further document and finalize.
Here is an example of how to try this out:
```[ereinecke@airwolf:~/github/OpenTimelineIO]$ virtualenv plugintest
[ereinecke@airwolf:~/github/OpenTimelineIO]$ virtualenv plugintest
[ereinecke@airwolf:~/github/OpenTimelineIO]$ source plugintest/bin/activate
(plugintest) [ereinecke@airwolf:~/github/OpenTimelineIO]$ pip install .
(plugintest) [ereinecke@airwolf:~/github/OpenTimelineIO]$ cd examples/sample_plugin/
(plugintest) [ereinecke@airwolf:~/github/OpenTimelineIO]$ pip install .
(plugintest) [ereinecke@airwolf:~/github/OpenTimelineIO]$ cd ../..
(plugintest) …
```

Setuptools plugins

---

README.md
setup.py

PySide2 is on PyPi as of a week ago.
This adds the PySide2 dependency underneath the 'view' key in extra_requires, as discussed in https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/269#issuecomment-398248375
Updated the README with instructions as well.

Add PySide2 to setup.py under view key

---

.codecov.yml
opentimelineio/exceptions.py
opentimelineio/plugins/manifest.py
tests/test_adapter_plugin.py
tests/test_media_linker.py
tests/test_serializable_collection.py

Found some missnamed exceptions thanks to improving the coverage score. Also omitted files that are not run during unit tests on travis since they won't qualify for code coverage.

Fix bugs revealed by or related to code coverage.

---

opentimelineio/plugins/manifest.py

Its possible for extern plugins (in particular, RV's `py-interp`) to not have `pkg_resources` on the python path. This should be ok, since it shouldn't need to access any plugins in order to write out a valid RV file.

Add guard if pkg_resources is not found.

---

opentimelineio/adapters/__init__.py
tests/test_adapter_plugin.py
tests/test_media_linker.py
tests/test_stack_algo.py

There was a bug in a couple of the tests that was causing test failures in certain environments where the OTIO environment variables were set but plugins were loaded via pip.  The tests weren't doing a good enough job of bookkeeping the state of the central `ActiveManifest`.

Fix subtle bug with several unit tests

---

MANIFEST.in
docs/index.rst
docs/tutorials/write-a-schemadef.md
opentimelineio/__init__.py
opentimelineio/core/__init__.py
opentimelineio/core/json_serializer.py
opentimelineio/core/serializable_object.py
opentimelineio/core/type_registry.py
opentimelineio/core/unknown_schema.py
opentimelineio/plugins/manifest.py
opentimelineio/plugins/python_plugin.py
opentimelineio/schema/__init__.py
opentimelineio/schema/schema_def.py
opentimelineio/schema/schemadef.py
opentimelineio/schemadef/__init__.py
tests/baselines/exampleSchemaDef.py
tests/baselines/example_schemadef.py
tests/baselines/schemadef_example.json
tests/test_schemadef_plugin.py
tests/test_unknown_schema.py

This PR adds a new SchemaDef plugin type.  A SchemaDef plugin can define one or more new OTIO schemas (or schemata if you prefer) which define first-class serializable OTIO objects and can be upgraded based on changes to the schema version number just like other OTIO schema-based objects.  
One possible use case is to define new schemas for studio-specific metadata objects which can be included in the clip "metadata" field.  For instance, our internal media linker plugin uses a few Pixar-specific schemas to provide metadata values which can be automatically upgraded when the schema version number increases.  Those Pixar-specific metadata schemas are defined in a single SchemaDef Python plugin and included by our plugin_manifest.json.

new SchemaDef plugin type to define site-specific schemas

---

opentimelineio/core/json_serializer.py

This fixes a subtle bug.  Sometimes the unknown schema encoder would be called properly, but in other environments, it would not be.  The encoder map was being used like a list, but the order of the entries was random when iterated using _ENCODER_MAP.items().  Changed to be an actual list of pairs, which is the way we need to use it to be able to override a general case with a more specific case that precedes it in the list.

bug fix in json_serializer: use ordered list of encoders

---

opentimelineio/core/composition.py
tests/test_composition.py

Add an internal children membership set for tracking as well as a new
__contains__ method to use the set when checking for membership.
(NOTE: This is mostly to encourage discussion. Feelings will not be hurt if this is not the preferred solution.)

Composition: Optimize internal membership tracking for searches

---

opentimelineio/console/otiocat.py
opentimelineio/console/otioconvert.py
opentimelineview/console.py

Adds commandline arguments to disable the media linker (or specify it) to:
- otiocat
- otioconvert
- otioview

Disable medialinker from commandline

---

opentimelineio/algorithms/stack_algo.py
opentimelineio/algorithms/track_algo.py
opentimelineio/schema/track.py
tests/test_composition.py

Flattening for timelines with many tracks/items was slow because `range_in_parent` was computed by walking through all previous items and summing their times.  This adds a function (`range_of_all_children`) that computes a map of item to range_in_parent, so you can do a look up rather than a compute to get the value.  This speeds up one particular case from 1600s to flatten down to 6s.

Optimizations for flatten (range_of_all_children)

---

opentimelineio/core/composable.py
opentimelineio/core/composition.py
opentimelineio/core/item.py
opentimelineio/core/json_serializer.py
opentimelineio/core/media_reference.py
opentimelineio/core/type_registry.py
opentimelineio/hooks.py
opentimelineio/media_linker.py
opentimelineio/opentime.py
opentimelineio/plugins/manifest.py
opentimelineio/plugins/python_plugin.py
opentimelineio/schema/clip.py
opentimelineio/schema/effect.py
opentimelineio/schema/schemadef.py
opentimelineio/schema/serializable_collection.py
opentimelineio/schema/stack.py
opentimelineio/schema/timeline.py
opentimelineio/schema/track.py
opentimelineio/schema/transition.py
opentimelineio_contrib/adapters/hls_playlist.py
opentimelineio_contrib/adapters/rv.py
tests/test_clip.py
tests/test_item.py
tests/test_opentime.py

This PR should address:
- #320 -- constructors now copy arguments, and `TimeRange.end_time_inclusive` returns a copy
- #338 -- (partially addressed by #341) -- Upgrade functions are sorted to ensure that they run in the right order
- Removed some unnecessary code in the JSON deserializer
- #349 -- RV adapter creates a copy of the environment rather than directly modifying os.environ.

Bugfixes: Issue 320, 338, and 349 (biggest feature: constructors copy values)

---

opentimelineio/core/composable.py
opentimelineio/core/composition.py
opentimelineio/core/item.py
tests/test_composable.py
tests/test_composition.py

The _parent pointer should be a weakref.  This also enforces that nothing outside of item should use the _parent pointer directly, things should go through `.parent()`

Use a weakref for _parent to prevent cycles.

---

.travis.yml
opentimelineio_contrib/adapters/tests/test_burnins.py
tox.ini

Rejiggered the travis/tox configuration:
- PyAAF installation happens in tox now, rather than travis.  Because tox builds itself a virtualenv, this makes it easier for tox to do the right thing.  Note that this only works for linux, because it has explicit paths to released files from github.   If we could get PyAAF from pip, this would be simpler.
- Travis tells tox which environment to run
- Adjusted the import name on Pillow, which seems to have changed in recent versions of the library.
- Added the mock library as a dependency (needed for several unit tests in core).
- Makes tests run with verbose printout so that its easier to see what/why things get skipped.
- Removed Python 3.7 testing from Tox (it wasn't in Travis anyways). If someone wants this, we should add it to both.

Add support for AAF unit tests in travis.

---

opentimelineio_contrib/adapters/advanced_authoring_format.py
opentimelineio_contrib/adapters/tests/test_aaf_adapter.py

In AAF, effects are represented as a wrapper object around the clip. When we turn this into an OTIO, we attempt to simplify the structure to remove this extra level of nesting (the effects are a list on the Clip, not a wrapper). This PR adds a unit test to check for this, and modifies the simplify logic to un-nest any Composition that has only 1 child.

Simplify AAF clip nesting when effects are found

---

docs/tutorials/write-a-schemadef.md

This fixes issue #379.  A critical change to one string in the plugin manifest example.

fix an error in the schemadef plugin tutorial

---

opentimelineio/console/otiocat.py
opentimelineio/console/otioconvert.py
tests/test_console.py

Turns out it was only added to otioview.  Now its present in `otiocat` and `otioconvert`.  You can use it like this:
```otiocat opentimelineio_contrib/adapters/tests/sample_data/simple.aaf -a simplify=False```

Add adapter arg commandline argument to otiocat and otioconvert.

---

opentimelineview/timeline_widget.py
tests/sample_data/nested_example.otio

This allows nested Tracks to open correctly when double clicked in otio view. We still run into #292 though.

Fix otioview's support for nested tracks

---

opentimelineio/adapters/otio_json.py
opentimelineio/core/json_serializer.py

The `sort_keys` argument was vestigial from when we were iterating on the development.  It won't be present in the C++ api, so I'm removing it from the API with this PR.

Remove sort_keys argument to json serializer to adapter.

---

docs/tutorials/architecture.md

Was reading the help guide (https://opentimelineio.readthedocs.io/en/latest/index.html) and there was a misspelling of the word "schema" as "shema".

Fixing misspelling typo in docs

---

opentimelineio/core/composition.py
opentimelineio/core/json_serializer.py
opentimelineio/core/serializable_object.py
opentimelineio/core/type_registry.py
opentimelineio/core/unknown_schema.py
tests/test_serializable_object.py

We exposed the `data` dictionary (really the backing of `SerializableObject`), but since that is likely to change in the C++ version, this hides that.  We're also hiding the `.update()` method, since it only seems to be used by internal implementation details that are also likely to change in the C++ version.

Hide deserialization methods of SerizableObject

---

opentimelineio_contrib/adapters/extern_rv.py

As well as a quick variable rename to make it more clear what's used in `_create_media_reference()`

Now passing track_kind to transition/dissolve creation

---

setup.py

We depend on relatively modern features inside the pip and setuptools libraries.  Ironically, `pip` and `setuptools` don't provide great tools for catching this and reporting this.  
- Require `pip` version of at least 6.0
- Require `setuptools` version of at least 20.5.0
- Also make the dev dependencies floating (`>=` rather than pinned to a specific version `==`)
Definitely open to comments on this.  Is this a harsh requirement on folks?  VFX Platform doesn't specify a `pip` or `setuptools` version, but it probably should.

Better dependency reporting for `pip` and `setuptools`

---

opentimelineio_contrib/adapters/advanced_authoring_format.py
opentimelineio_contrib/adapters/tests/test_aaf_adapter.py
tox.ini

This is an initial (and somewhat messy, but working!) port in advanced_authoring_formay.py of pyaaf to pyaaf2. All tests pass locally.

Initial port of aaf adapter from using pyaaf to pyaaf2

---

opentimelineio/core/composable.py
opentimelineio/core/composition.py
opentimelineio_contrib/adapters/advanced_authoring_format.py
tests/test_composable.py
tests/test_composition.py
tests/test_stack_algo.py

If you have an item whose `.parent()` is not `None`, it is now a ValueError to add it to another composition.  You need to remove it from the other composition before adding it to the new one.  This is to anticipate an implementation detail of the C++ API.

Moving already parented item is an error

---

opentimelineio/core/serializable_object.py
opentimelineio_contrib/adapters/hls_playlist.py
opentimelineio_contrib/adapters/tests/test_hls_playlist_adapter.py
tests/test_composition.py
tests/test_item.py
tests/test_serializable_object.py
tests/test_track_algo.py

Again, anticipating the C++ implementation, we are removing the shallow copy function.  It doesn't look like anyone in the code base was using it.

Remove the copy() method and make __copy__ an error.

---

opentimelineio/core/composition.py
tests/test_composition.py

There was a bug in `trimmed_range_in_parent` that was causing a crash when the item was trimmed out of the parent.  Now it correctly returns `None` and has a unit test for this.

Add test and fix for trimmed_range_in_parent when the item is trimmed out

---

opentimelineview/timeline_widget.py

- We added the range_of_all_children method for exactly this use case- it was missing here
- This _significantly_ improves performance of reading large files into otioview

Fix N^2 (over items) performance in otioview _populate

---

opentimelineio_contrib/adapters/advanced_authoring_format.py

With the change in https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/410 `_extract_timecode_info` could potential return startTime as None. 
It'll trigger error like this:
File "/Users/jchen/scratch/gitlab/transmogrifier2/lib/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 262, in _transcribe startTime += timecode_start TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
I ran into this several days ago. I will upload an example somewhere accessible.

Guard against `timecode_start` is None

---

opentimelineio_contrib/adapters/contrib_adapters.plugin_manifest.json
opentimelineio_contrib/adapters/tests/sample_data/xges_example.xges
opentimelineio_contrib/adapters/tests/test_xges_adapter.py
opentimelineio_contrib/adapters/xges.py

This implement the basic for a "xges" adapter, the native [GStreamer Editing Services] serialization format.
I have already implemented a [GESFormatter](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-editing-services/html/GESFormatter.html) to be able to take advantage of the otio formatter in any project using GES. I am not sure if it belongs to otio itself or GES, what would you prefer?
Also note that in GES each and every timestamp is a GstClockTime (a.k.a `long unsigned int`) representing times in nanoseconds, this lead to big approximation because of the nature of times representation in otio. Note that this "restriction" in GES is being worked on and we plan on introducing a mode where we would work with rational time exclusively (see [this …

GStreamer Editing Services XML adapter

---

opentimelineio_contrib/adapters/advanced_authoring_format.py
setup.py

Some changes (c77bbb1, 5b2cfa5) in PyAAF2 hasn’t been in a versioned tag yet.
We need to update OTIO’s pinned pyaaf2 version (from 1.1.0) to make this working properly.

Use PyAAF2’s `def walk()`.

---

opentimelineio/console/otioconvert.py

- fixes the track selection in `otioconvert`, which was broken when we switched the parenting rules
- adds support for -A to send arguments to the output adapter as well.

otioconvert fixes output adapter arguments

---

opentimelineio/algorithms/__init__.py
opentimelineio/algorithms/timeline_algo.py
opentimelineio/console/otioconvert.py
tests/test_timeline_algo.py

- Adds `--begin` and `--end` arguments to `otioconvert` shell program, which lets you trim out everything outside the range described by the begin/end arguments
- Also adds a `timeline_algo.py` module with a convenience wrapper around `track_trimmed_to_range`

Add timeline trimming feature to `otioconvert`

---

opentimelineio/algorithms/__init__.py
opentimelineio/algorithms/stack_algo.py
opentimelineio/core/composition.py
opentimelineio/core/item.py
opentimelineio/schema/stack.py
opentimelineio/schema/track.py
tests/test_composition.py
tests/test_stack_algo.py
tests/test_timeline.py

- Combining #373 w/ #358 
- Also refactors `top_child_..` into algorithms
- This speeds performance of iterating over `each_child` with a search range considerably (in a test with a full feature film timeline, from 691s to 0.8s)
- Adds documentation
- Adds an implementation of `range_of_all_children` on stack so that it can be called recursively.
(Big thanks to @alatdneg, this just built off his work)

Optimize `each_child` when used with the `search_range` option

---

README.md

We've moved from travis.org to travis.com.

Update travis link to new integration.

---

opentimelineio/adapters/cmx_3600.py
tests/sample_data/nucoda_example.edl
tests/test_cmx_3600_adapter.py

Stashes the clip_handlers `reel` in the cmx_3600 metadata so it can be recalled when written back out by the cmx_3600 adapter
Also added a test event that `round trips` the sample nucoda edl while maintaining the REEL(SOURCE_ID) field
~BREAKING CHANGE: had to update the nucoda sample edl to match the output format, which includes a new line after Title.  May or may not effect others using that sample~

Store the REEL variable in the cmx_3600 metadata when not `AX`

---

opentimelineio/core/composition.py
tests/test_composition.py

Inserting to a composition with a slice was omitting members from the `_child_lookup` set.  This fixes that bug, and hopefully addresses #436.

Fix slice insert membership bug

---

docs/tutorials/architecture.md

The "Read the Docs" rendered architecture.html contains a dead link to the write an adapter docs. Corrected the link URL in this PR.

Fix deadlink in architecture.md

---

opentimelineview/console.py
opentimelineview/timeline_widget.py

new feature for otioviewer => frame_all at start.

Add frame all function.

---

opentimelineio_contrib/adapters/advanced_authoring_format.py
opentimelineio_contrib/adapters/tests/test_aaf_adapter.py

Continued tuning of the AAF simplifier. #384

Prevent stranded clips from appearing in the top level stack.

---

docs/tutorials/write-a-hookscript.md
opentimelineio/adapters/adapter.py
tests/baselines/adapter_plugin_manifest.plugin_manifest.json
tests/test_hooks_plugins.py

This MR passes through the  argument maps in the adapter.py read/write systems, passing them through to the hooks.
The existing #TODO items suggested that we perhaps should be doing this...
I can't find any reason not to.
An example use-case would be to create a pre-write adapter hook that checks the argument map for `style` being identified as _nucoda_ and then preforms a path replacement on the reference url
```pyhthon
def hook_function(in_timeline,argument_map=None):
if argument_map.get('style') == 'nucoda':
for in_clip in in_timeline.each_clip():
''' Change the Path to use windows drive letters ( Nucoda is not otherwise forward slash sensative ) '''
if in_clip.media_reference:
in_clip.media_reference.target_url = in_clip.media_reference.target_url.replace(r'/linux/media/path','S:') …
```

Update the adapter.py to pass Argument Maps to Hooks

---

opentimelineio_contrib/adapters/aaf_adapter/aaf_writer.py
opentimelineio_contrib/adapters/advanced_authoring_format.py
opentimelineio_contrib/adapters/tests/test_aaf_adapter.py

Creating abstract method _transition_parameters that is called in _TrackTranscriber.aaf_transition to support both video and audio transitions
side note: Using metadata clip length instead of duration() in aaf_sourceclip. We'll fix this later
Co-authored-by: Freeson Wang <freeson@pixar.com>

AAF writer: Adding support for audio transitions

---

opentimelineio_contrib/adapters/tests/test_aaf_adapter.py

Co-authored-by: Freeson Wang <freeson@pixar.com>

Remove unneeded import of aaf2 in test_aaf_adapter

---

opentimelineview/timeline_widget.py

- Ruler.map_to_time_space methods now use item.trimmed_range() instead of relying on item.source_range.start_time which might not exist.
- Adjust Ruler.map_to_time_space to show the correct last frame number (it was offset by +1 before)
-Modify Ruler.init to order the items per track based on their start_frame. Before I was wrongly relying on track.childItems to return the items in the order they were created.
- Initialize the nametuple self._bounder_data in Ruler.__init__ rather than instancing it on each call of Ruler.map_to_time_space. This was slowing down the execution.

Ruler - fix bug

---

opentimelineio_contrib/adapters/tests/test_xges_adapter.py
opentimelineio_contrib/adapters/xges.py

an effort to get a clean output from `make lint`

Linting for xges adapter and the xges test

---

opentimelineview/timeline_widget.py

1. Add an **Effect** Widget to easily spot clips with effects in the *otioviewer*.
2. Center the *source_name_label* in the track. Before it was sitting at 1/3 of its height and would have partially overlap with the **Effect** widget.
3. Display the latest *inclusive* frame rather than the latest *exclusive* frame. Now the last frame number on a clip matches the frame number from the *ruler*.

Add Effect Widget.

---

opentimelineio_contrib/adapters/extern_rv.py
opentimelineio_contrib/adapters/tests/sample_data/screening_example.rv
opentimelineio_contrib/adapters/tests/sample_data/transition_test.rv
opentimelineio_contrib/adapters/tests/test_rvsession.py

For discussion, but coming out of #363, this alternate approach will hide any video that might be coming through via an "Audio" track kind.

Prepending blank movieproc to audio track sources in RV to hide any video

---

opentimelineio/console/__init__.py
opentimelineio/console/console_utils.py
opentimelineio/console/otiocat.py
opentimelineio/console/otioconvert.py
opentimelineview/console.py
tests/test_console.py

Adds:
- support for `-M foo=bar` media linker arguments to `otiocat`, `otioconvert`, `otioview`
- refactors code to turn `foo=bar` arguments into a `console_utils.py` module
- cleanup & linting.

Add media linker arguments to commandline tools

---

opentimelineview/console.py
opentimelineview/ruler_widget.py
opentimelineview/timeline_widget.py
opentimelineview/track_widgets.py

- The **navigation** menu allows specifying which elements the arrow keys will snap on.
- **Highlight**. When an element is selected, its border becomes green. Now, the thickness of the border is thicker for better readability in mac. The thickness of the border is set by default to 5.
```python
HIGHLIGHT_WIDTH = 5
```
- Refactor how the navigation works. It does not rely on the pyside call *QtWidgets.QGraphicsScene.itemAt* any more but uses the otio methods to navigate from a otio item to another one.
- in *timeline_widget._BaseItem*, the pen is set to pen.setCosmetic(True) so the thickness of the border is not affected by the zoom.
- Ensure that a selected *timeline_widget._BaseItem* is always on the front.
- Minor changes in *timeline_widget.Ruler*. A lambda has been redefined as a …

Add Key Navigation Filter Menu

---

opentimelineio/opentime.py
tests/test_opentime.py

Hey!
This PR should produce the result @reinecke is after in #476 
When passing an NDF timecode with a DF frame Rate to `opentime.from_timecode` calculation respects the NDF TC and does not remove frames.

Suggested fix for #476

---

opentimelineio/schema/timeline.py
tests/baseline_reader.py
tests/baselines/empty_timeline.json
tests/test_fcp7_xml_adapter.py

- Also add the ability to layer over baselines in tests
- global_start_time has a default value with a rate of 24

Add global_start_time as a serializable_field.

---

opentimelineio_contrib/adapters/advanced_authoring_format.py
opentimelineio_contrib/adapters/tests/test_aaf_adapter.py

This PR adds support for reading Timeline's global_start_time from AAF files.

AAF reader supports Timeline global_start_time

---

opentimelineio_contrib/adapters/aaf_adapter/aaf_writer.py

This value is shown as track name in the Media Composer.
pyaaf2 gave default name as `"Track-%03d" % slot_id`. Here we just pass whatever name a track has to mobslot.
If the name is None, the Media Composer does not show the name (after `/`), but still labels the track as V1, V2 for video tracks and A1, A2 for audio tracks.

Pass track name to mobslot

---

opentimelineio_contrib/adapters/aaf_adapter/aaf_writer.py
opentimelineio_contrib/adapters/tests/test_aaf_adapter.py

Without this, the resulting AAF always use the full available media of a clip even the start_time in source_range has different value than that of availabe_range.
I will make a test case for this fix.

Fix missing source clip start offset

---

setup.py

This should address a vulnerability flagged by Snyk.
https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174323

Require a recent version of urllib3.

---

docs/tutorials/write-a-schemadef.md
opentimelineio/schema/schemadef.py
tests/test_schemadef_plugin.py

- Currently, schemadefs are only loaded implicitly, either by reading a file that contains the schemadef or by calling `ActiveManifest()` or `otio.schema.schemadef.from_name().module()`.
- This PR adds a function `otio.schema.schemadef.module_from_name()` that makes it easy to explicitly load a plugin.
- This also clarifies the unit tests around how schemadefs get loaded and adds some documentation about how to use this function.

Add function to explicitly load SchemaDef plugins

---

opentimelineio_contrib/adapters/aaf_adapter/aaf_writer.py
opentimelineio_contrib/adapters/tests/sample_data/precheckfail.otio
opentimelineio_contrib/adapters/tests/test_aaf_adapter.py

This addresses #484 (not fixing it, but making the failure more elegant).
The validate_metadata() function requires access and verification of certain fields in objects that may or not be there. I thought that using a "promise" like pattern led to a much more elegant, robust result. Hopefully this isn't too much overkill, it does allow our precheck to be a lot more expressive.

AAF Writer: Making precheck() more robust

---

opentimelineio/adapters/fcp_xml.py
tests/sample_data/premiere_example_filter.json
tests/sample_data/premiere_example_filter.xml
tests/test_fcp7_xml_adapter.py

This is a refactor of the FCP XML adapter adapter. The goal of this refactor was to:
- Address some timing accuracy issues that could be encountered
- Add support for handling effects and generators
- Add support for parsing and roundtripping FCP XML metadata
This is expected to address the following issues (I would love confirmation from the relevant parties):
- #468 
- #265 
- #334 
- #287 
- #485

Refactor FCP XML adapter - add generator and effect support

---

opentimelineio_contrib/adapters/aaf_adapter/aaf_writer.py
opentimelineio_contrib/adapters/tests/sample_data/gaps.otio
opentimelineio_contrib/adapters/tests/test_aaf_adapter.py

This simple change is to address cases where the track has all gaps and does not have proper "clip"s

AAF Writer: To get the edit rate, look at the first "child" not the first "clip".

---

opentimelineio_contrib/adapters/advanced_authoring_format.py

During _transcribe(), we store just one parent. This is great, but it would be even better to have the entire parent chain available - both for debugging and perhaps for logic. I believe there is at least one if statement which really wants to say "am I a clip in the CompositionMob", which would now be made a lot easier by this change.

AAF Reader: simplify source_range and available_range in transcribe() of SourceClip

---

src/py-opentimelineio/opentimelineio/core/__init__.py
src/py-opentimelineio/opentimelineio/core/composable.py
src/py-opentimelineio/opentimelineio/core/composition.py
src/py-opentimelineio/opentimelineio/core/item.py
src/py-opentimelineio/opentimelineio/core/mediaReference.py
src/py-opentimelineio/opentimelineio/opentime.py
src/py-opentimelineio/opentimelineio/schema/__init__.py
tests/test_opentime.py

Currently the C++ branch uses `from opentimelineio import _otio` to fetch the C++ modules.  This moves to using relative imports.

move to relative imports for fetching names from the C++ code.

---

src/opentimelineio/version.h

This adds an "OTIO_NS" macro as a shorthand for the full "opentimelineio::OPENTIMELINEIO_VERSION" namespace.

[opentimelineio] add OTIO_NS convenience macro for C++ clients

---

docs/tutorials/otio-serialized-schema.md
opentimelineio/console/autogen_serialized_datamodel.py

Docstrings for attributes in python don't really exist.  Instead of
fetching them, the autodoc generator now just uses "" as the docstring
for properties that it has to read off the instantiated object.

Clean up auto-docstrings.

---

setup.py

When the user specifies `--user` we have to make sure to use
the usersite package directory instead of letting cmake install
lib systemwide.
Without that I am getting a permission issue:
```
-- Install configuration: "Release"
CMake Error at src/opentime/cmake_install.cmake:47 (file):
file cannot create directory:
/usr/lib/python3.7/site-packages/opentimelineio/cxx-libs/lib.  Maybe need
administrative privileges.
Call Stack (most recent call first):
src/cmake_install.cmake:43 (include)
```

Fix installing in user prefix when --user is specified

---

contrib/opentimelineio_contrib/adapters/fcpx_xml.py
contrib/opentimelineio_contrib/adapters/tests/test_fcpx_adapter.py

Getting this stack trace otherwise:
```
File "gesotioformatter.py", line 44, in do_save_to_uri
File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio/adapters/__init__.py", line 194, in write_to_file
**adapter_argument_map
File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio/adapters/adapter.py", line 179, in write_to_file
result = self.write_to_string(input_otio, **adapter_argument_map)
File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio/adapters/adapter.py", line 243, in write_to_string
**adapter_argument_map
File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio/plugins/python_plugin.py", line 128, in …
```

fcpx: Decode output of ffprobe before using it as string

---

contrib/opentimelineio_contrib/adapters/xges.py

The tracks should be loaded in reverse order for the XGES format.
Also in GES, layers (tracks in otio terms) do not have a track type
(tracks are global to the timeline which formalizes the outputed
types), thus we should try to keep audio and video tracks in the same
order during de-serialization.

xges: Fix tracks ordering

---

docs/tutorials/adapters.md

Just fixing an oversight - when we moved to pyaaf2 we forgot to update the docs with new instructions on how to get the library and use it with OpenTimelineIO

Update docs for pyaaf2

---

CMakeLists.txt
setup.py
src/CMakeLists.txt
src/deps/CMakeLists.txt

Add code in the CMake build system to automatically run `git submodule update`.  
Addresses #553

Detect submodules not synced

---

src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py
tests/test_fcp7_xml_adapter.py

Some softwares don't add the `<NTSC>` element to the `<rate>` element if the framerate
is not NTSC. Check if the element can be found before trying to
check it's value.

FCP XML: Adds a check on the NTSC element before reading its value

---

src/opentime/rationalTime.cpp
tests/test_opentime.py

- addresses a subtle bug in the `to_time_string` method on rationalTime
- old implementation would strip leading `0`s from the fractional compenent of the seconds field of the ffmpeg time string, for example `27.08333` would become `27.8333`.
- More closely matches the product of the python implementation

Rebuild float serializer for ffmpeg time string

---

src/opentimelineio/anyDictionary.h
src/opentimelineio/composition.cpp
src/opentimelineio/item.cpp
src/opentimelineio/serializableObject.h
src/opentimelineio/typeRegistry.cpp

This addresses a compilation issue in OTIO client code where assert() can go
undeclared if assert.h does not get included indirectly from another header.
It also removes one case in serializableObject.h where assert.h was included
but not actually needed.

[opentimelineio] add include of assert.h where assert() is used

---

src/opentimelineio/composition.cpp
src/opentimelineio/deserialization.cpp
src/opentimelineio/serialization.cpp
src/opentimelineio/transition.cpp
src/opentimelineio/typeRegistry.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_utils.cpp

This cleans up a bunch of unused parameter warnings seen when using gcc 4.8.3
and compiling with -Wextra.

[opentimelineio] fix unused parameter compilation warnings

---

contrib/opentimelineio_contrib/adapters/contrib_adapters.plugin_manifest.json
contrib/opentimelineio_contrib/adapters/tests/tests_xges_adapter.py
contrib/opentimelineio_contrib/adapters/xges.py

Added custom schemas to be used both internally by xges and externally by users.
The two added schemas are:
+ `XgesTrack`, which stores attribute data corresponding to xges track elements (which are quite distinct from otio.schema.Tracks); and
+ `GstStructure`, which emulates the GstStructure used in the GStreamer/GES C library, which primarily means it can read the `properties` and `metadatas` attributes of the xges elements, as well as successfully create them.
The reason for creating these as schemas is that they will eventually be used in the metadata of otio core elements for conversion purposes. For example, currently the xges `properties` and `metadatas` attributes are stored in the otio metadata as serialized strings. If this was replaced with the `GstStructure` schema, the data …

xges: schemas

---

src/CMakeLists.txt
src/opentime/CMakeLists.txt
src/opentime/rationalTime.cpp
src/opentime/timeRange.h
src/opentimelineio/CMakeLists.txt
src/opentimelineio/stringUtils.cpp
src/opentimelineio/stringUtils.h

Various fixes to successfully compile OpenTimelineIO with Visual Studio 2019. A separate pull request will be made to address the compiler warnings.

Fixes for building with Visual Studio 2019

---

README.md

- There were some outdated lines in the readme:
- no more Cxx branch
- `-e` branch is currently broken, removed that from the development instructions in the python section
- added `code` formatting to instructions
- added note about the viewer program installation instructions being in the quickstart section

Update the C++ instructions in the README

---

src/opentimelineio/serialization.cpp
tests/test_serializable_object.py

Fixes #578 
The any dictionary equality function was walking over the left
dictionary and incrementing an iterator.  To make sure that the
dictionaries are equivalent, checking to make sure that the end of BOTH
dictionaries has been reached at the end of the function instead of just
the left dictionary should correct the symmetry of is_equivalent_to.

Ensure that dictionary comparison is symmetrical

---

src/CMakeLists.txt
src/opentime/rationalTime.cpp
src/opentimelineio/deserialization.cpp
src/opentimelineio/errorStatus.h
src/opentimelineio/serialization.cpp
src/opentimelineio/stackAlgorithm.cpp
src/opentimelineio/stringUtils.cpp
src/opentimelineio/track.cpp
src/opentimelineio/trackAlgorithm.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_utils.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_utils.h

These changes fix all warnings when compiling with Visual Studio 2019. Note that I bumped PyBind11 to C++14 on Windows, since it looks like C++11 isn't supported by PyBind11 on Windows (I was getting "/std:c++11" argument not recognized warnings when compiling the Python bindings):
https://pybind11.readthedocs.io/en/stable/compiling.html#configuration-variables

Fix warnings for Visual Studio 2019

---

contrib/opentimelineio_contrib/application_plugins/rv/example_otio_reader/PACKAGE
contrib/opentimelineio_contrib/application_plugins/rv/example_otio_reader/example_otio_reader_plugin.py
contrib/opentimelineio_contrib/application_plugins/rv/example_otio_reader/otio_reader.py
setup.cfg

Re-creating #395 as an example RV plugin for loading an OTIO file into the current RV context.

Example RV OTIO reading application plugin

---

src/opentimelineio/serializableObject.cpp
tests/test_adapter_plugin.py
tests/test_builtin_adapters.py
tests/test_console.py

A number of the core tests (OTIO_DISABLE_SHELLOUT_TESTS=true) were failing on Windows, this pull request has two changes to fix that.
Tests were crashing on exit with the error message, "d:\agent\_work\2\s\src\vctools\crt\crtw32\stdcpp\thr\mutex.c(64): mutex destroyed while busy". To fix this I unlocked the mutex in serializableObject.cpp before it is deleted.
Tests with temporary files were failing since the C++ code could not reopen the files opened by Python (this is mentioned as a caveat in the docs for tempfile.NamedTemporaryFile()). Since the Python tests don't actually need the file object, just the file name, I replaced using NamedTemporaryFile() with temporary directories that Python then passes to C++ along with a file name.

Fix tests for Visual Studio 2019

---

src/opentime/rationalTime.cpp
tests/test_opentime.py

RationalTime object to a string.
Before this change, doing
negativeRationalTime = otio.opentime.RationalTime(-24,24)
timeString = otio.opentime.to_time_string(negativeRationalTime)
timeString would be "-1:-1:-10", which is not a useful time string.
This change introduces a 'negative' time string, i.e. generate the
same string value as a positive RationalTime value would do but
with a '-' sign in front of the string:
timeString is now: '-00:00:01.0'
This is actually a valid string format for ffmpeg and useful if you
for example want to add silence to an audio file at the beginning.

Adding support for negative time strings when converting a negative

---

docs/cxx/bridges.md
docs/cxx/cxx.rst
docs/cxx/older.md
docs/index.rst

Adds documentation by @davidbaraff on the design and implementation of the C++ core and pybind11 wrapper.
Co-authored by: @davidbaraff

Add C++ docs to repository

---

.readthedocs.yml
setup.py

RTD is getting a crazy traceback in setup.py.  from this line:
```
File "/tmp/pip-req-build-i6tc3y8j/setup.py", line 253, in <module>
distutils.version.StrictVersion(SETUPTOOLS_VERSION)
File "/home/docs/checkouts/readthedocs.org/user_builds/opentimelineio/conda/latest/lib/python3.7/distutils/version.py", line 40, in __init__
self.parse(vstring)
File "/home/docs/checkouts/readthedocs.org/user_builds/opentimelineio/conda/latest/lib/python3.7/distutils/version.py", line 137, in parse
raise ValueError("invalid version number '%s'" % vstring)
```
Doing some googling on `StrictVersion` vs `LooseVersion`, it sounds like what we really want is `LooseVersion`?  If python packaging folks know more, please speak up!
Also bumping RTD to use python3.7 instead of 3.6.

RTD is breaking on StrictVersion in setup.py

---

contrib/opentimelineio_contrib/adapters/contrib_adapters.plugin_manifest.json
contrib/opentimelineio_contrib/adapters/kdenlive.py
contrib/opentimelineio_contrib/adapters/tests/sample_data/kdenlive_example.kdenlive
contrib/opentimelineio_contrib/adapters/tests/test_kdenlive_adapter.py
docs/tutorials/otio-plugins.md

Hello,
Here is a proposal to be able to inter-operate with the libre video editor Kdenlive.
I've run some successful tests on my side, and our community is waiting for such feature for long.
Please guide me if I have to do something more.
Many thanks for OpenTimelineIO!
BR,
Vincent

Add Kdenlive adapter

---

docs/cxx/cxx.rst

- Added documentation for best practices on schema read errors
- Created a table outlining C++ error types, how they map to python exceptions, and some semantic description
The error chart may or may not be a good idea. I'd also look to others to help fill in the semantic meanings for some of the errors to make sure I don't write something misleading.
This also poses the question about when it's appropriate to add additional errors. If we tackle that, then it'd be good to outline the steps one should take when doing that.

C++ Error documentation additions

---

docs/tutorials/otio-serialized-schema-only-fields.md
docs/tutorials/otio-serialized-schema.md
src/opentimelineio/CMakeLists.txt
src/opentimelineio/imageSequenceReference.cpp
src/opentimelineio/imageSequenceReference.h
src/opentimelineio/typeRegistry.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp
src/py-opentimelineio/opentimelineio/schema/__init__.py
src/py-opentimelineio/opentimelineio/schema/image_sequence_reference.py
tests/test_image_sequence_reference.py

This is meant to be an alternate approach to the one @apetrynet took in pr #536 as a point of discussion. This resolves #69. I wanted to try an approach that more explicitly broke out image sequence parameters and had awareness of timing associated with frames. This also avoids using format strings in urls which could become ambiguous or need complex escaping logic if a url encoding includes a `%` (e.x. `%20` for a space).
The image sequence is expressed with:
- `target_url_base` - everything leading up to the file name in the `target_url`
- `name_prefix` - everything in the file name leading up to the frame number
- `name_suffix` - everything after the frame number in the file name
- `start_frame` - first frame number used in file names
- `frame_step` - step between frame numbers in file …

Initial implementation of ImageSequenceReference

---

src/opentimelineview/console.py
src/py-opentimelineio/opentimelineio/console/otiocat.py
src/py-opentimelineio/opentimelineio/console/otioconvert.py

Adding access to the Hooks Arguments from `otioview` and `otioconvert`
I used the -H switch, which I think is appropriate as long as no one confuses it with the `--help` switch

Add hook function args to otioview and otioconvert

---

src/opentime/rationalTime.cpp
tests/test_opentime.py

Fix: #606 
This addresses the issue as written... but because having an implicit `rescale` in `to_timecode` seems iffy, I'm also proposing another PR that drops the `rate` argument from `to_timecode` entirely in favor of explicitly calling `rescale_to` in calling code.  Thoughts?

Timecode rate is ignored

---

contrib/opentimelineio_contrib/adapters/kdenlive.py

Hello,
A minor change that avoids unicode/utf-8 XML encoding failures when switching between python2 & python3.
Best regards,
Vincent

fix otioconvert for Kdenlive with python3

---

docs/tutorials/otio-plugins.md
src/py-opentimelineio/opentimelineio/adapters/otio_json.py

Not at all critical, but this threw me for a bit and I thought it might be nice to expose here.

Expose json indent to the otio_json adapter

---

contrib/opentimelineio_contrib/adapters/extern_rv.py
contrib/opentimelineio_contrib/adapters/tests/sample_data/rv_metadata.otio
contrib/opentimelineio_contrib/adapters/tests/sample_data/rv_metadata.rv
contrib/opentimelineio_contrib/adapters/tests/sample_data/screening_example.rv
contrib/opentimelineio_contrib/adapters/tests/sample_data/transition_test.rv
contrib/opentimelineio_contrib/adapters/tests/test_rvsession.py
contrib/opentimelineio_contrib/application_plugins/rv/example_otio_reader/otio_reader.py

This is the start of a discussion around changes to how the rv adapter stores metadata.
This first part is me trying to align the example rv plugin and this adapter with the location of where the metadata is stored in the rv session by changing it from "attributes.otio_metadata" to "otio.metadata". The thinking here is that the would allow future other properties in the "otio" namespace in the rv session. This does break any existing consumers of this data though. 
Next, I want to have a discussion on the best way to serialize the meatadata so I am leaving this as WIP for now. 
-Robyn

RV adapter metadata updates

---

src/py-opentimelineio/opentimelineio/adapters/cmx_3600.py
tests/sample_data/multi_audio.edl
tests/test_cmx_3600_adapter.py

Fixed issue where CMX3600 adapter would try to add the same clip to multiple tracks.
Also addressed an issue where certain clip properties were being set up in per-track a loop when they didn't need to be.
Fixes #642

CMX3600: Fixed issue with clips going to multiple target tracks

---

CMakeLists.txt
README.md
docs/tutorials/quickstart.md
src/CMakeLists.txt
src/opentime/CMakeLists.txt
src/opentimelineio/CMakeLists.txt

Add a bin target to satisfy cmake windows requirement, bump the version to cmake 3.
The cmake version for Linux is per vfx-platform 2018, the version for Windows is the latest, otherwise VS2019 can't be supported.

Fix the windows build

---

examples/conform.py

Add list of supported files to tooltip for the conform.py example script.

Add List of Supported Formats to Conform.py Help Text

---

contrib/opentimelineio_contrib/adapters/tests/tests_xges_adapter.py
contrib/opentimelineio_contrib/adapters/xges.py
docs/tutorials/otio-plugins.md

Adds effects and markers support to the xges adapter.
GESEffects found below an xges clip translate to otio item effects.
GESMarkers found in an xges timeline translate to otio stack markers.
Also:
+ GstStructure was improved
+ GstCaps and GstCapsFeatures schemas were added
+ added tests
+ made small fixes and tidies

xges: Effects and Markers Support

---

src/opentimelineview/ruler_widget.py
src/opentimelineview/timeline_widget.py
src/opentimelineview/track_widgets.py

Fixes #654 
I've removed the exclusion check for empty tracks and also displayed the name of the Tracks along with the kind of track.
Here's how it looks:
After changing the code I've introduced a bug in the FrameNumber displayed on the slider. I'll fix that tomorrow.
Meanwhile I look forward to your thoughts on this.
@jminor @ssteinbach @reinecke

Indicate Empty track in otioview and display track name

---

src/py-opentimelineio/opentime-bindings/opentime_timeRange.cpp
tests/test_opentime.py

The bindings for `__deepcopy__` on `TimeRange` previously didn't accept the `memo` arg. This was causing the following error:
```
>>> copy.deepcopy(otio.opentime.TimeRange())
File "<stdin>", line 1, in <module>
File "/Users/ereinecke/.newt-cache/pyenv/versions/3.8.2/lib/python3.8/copy.py", line 153, in deepcopy
y = copier(memo)
TypeError: __deepcopy__(): incompatible function arguments. The following argument types are supported:
1. (self: opentimelineio._opentime.TimeRange) -> opentimelineio._opentime.TimeRange
Invoked with: otio.opentime.TimeRange(start_time=otio.opentime.RationalTime(value=0, rate=1), duration=otio.opentime.RationalTime(value=0, rate=1)), {}
```
I've also added unitests for copy and deepcopy on `RationalTime` and `TimeRange` to …

Fixed deepcopy for opentime.TimeRange

---

contrib/opentimelineio_contrib/adapters/fcpx_xml.py
contrib/opentimelineio_contrib/adapters/kdenlive.py
contrib/opentimelineio_contrib/adapters/tests/test_hls_playlist_adapter.py
contrib/opentimelineio_contrib/adapters/tests/test_maya_sequencer.py
contrib/opentimelineio_contrib/adapters/xges.py
src/py-opentimelineio/opentimelineio/adapters/cmx_3600.py
src/py-opentimelineio/opentimelineio/console/autogen_plugin_documentation.py
src/py-opentimelineio/opentimelineio/core/_core_utils.py

Somehow lint started failing for people on a lot of their branches due to issues in master, here is one such example: https://travis-ci.com/github/PixarAnimationStudios/OpenTimelineIO/jobs/333466701
Worth noting, there was one function in the kdenlive adapter I didn't know the correct fix for so I just muted the warning. This is likely broken and will require someone with more experience in that realm to address:
```
def write_keyframes(kfdict):
"""Build a MLT keyframe string"""
return ';'.join('{}={}'.format(str(int(t.value))).format(v)  # noqa: F524
for t, v in kfdict.items())
```

Addressing a handful of lint issues.

---

src/opentimelineview/track_widgets.py

@ssteinbach as per your suggestion to have an option to view long track names in otioview, I've added an option to do that on double-clicking on the TrackName widget.
This is how it looks:

Toggle 'complete track name' display on double click in otioview

---

Makefile
docs/conf.py
docs/cxx/cxx.rst
docs/cxx/older.md
docs/tutorials/architecture.md
docs/tutorials/contributing.md
docs/tutorials/otio-file-format-specification.md
docs/tutorials/otio-plugins.md
docs/tutorials/write-a-hookscript.md
docs/tutorials/write-a-schemadef.md
docs/tutorials/write-an-adapter.md
src/py-opentimelineio/opentimelineio/adapters/otio_json.py

It turns out that we needed to add the "recommonmark" plugin to our plugins in sphinx to get the code blocks to get rendered correctly from markdown files.
- Also add code language annotations to code blocks in the documentation
- Fix the formatting on some of the examples
The bug this fixes is the table of contents looking like this:
(note all the `{` in the table of contents)
For a preview of this, see:
https://opentimelineio-ssteinbach.readthedocs.io/en/documentation_busted_rtd/

Fix documentation on read the docs

---

docs/tutorials/quickstart.md

- formatting was confusing the table of contents.  This should look nice
now.
- Also add syntax highlighting for code examples

Clean up developer quickstart

---

contrib/opentimelineio_contrib/adapters/extern_rv.py
contrib/opentimelineio_contrib/application_plugins/rv/example_otio_reader/otio_reader.py

This syncs the example OTIO reader plugin with the recent changes in the RV adapter wrt support for the ImageSequenceReference schema

Added support for ImageSequenceReference to example RV plugin

---

contrib/opentimelineio_contrib/adapters/kdenlive.py
contrib/opentimelineio_contrib/adapters/tests/sample_data/kdenlive_example.kdenlive

Hello,
Sorry this effects conversion was a forgotten draft (does any effects mapping exist?), it was not tested in the sample project.
I thought of removing the function entirely, but I think keeping it in place can be interesting for future extension...
Thanks for raising the issue!

Fix #703 mlt keyframe string decoding/encoding

---

tests/test_clip.py
tests/test_media_reference.py

I think instead of the line I removed, it might be `self.assertIsNot(cl.source_range, tr)`.

Remove redundant comparison in clip tests

---

src/py-opentimelineio/opentimelineio/adapters/cmx_3600.py
tests/test_cdl.py

Encountered a CDL variant where SOP values looked like:
`(1.0801, 1.0747, 1.0730)`
as opposed to:
`(1.0801 1.0747 1.0730)`
Updated CDL value regex to accept this.

Added support for comma separated CDL SOP values

---

setup.py

update pyaaf2 pin to use 1.4.0 (latest pyaaf2 release). This contains some important fixes
(like understanding the pulldown AAF object) required for some upcoming AAF Reader changes.

Update pyaaf2 pin to 1.4.0

---

contrib/opentimelineio_contrib/adapters/hls_playlist.py

Looking to move away from terms that could be viewed as racially charged - hopefully this suggestion is ok.
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

Change hls_md_blacklist -> hls_md_rejectlist

---

src/py-opentimelineio/opentimelineio/schema/marker.py
tests/test_marker.py

It appears the `__str__` and `__repr__` methods may have been copy/pasted from Clip by accident in the C++ port, printing in the python REPL would result in a traceback like:
```
File "<stdin>", line 1, in <module>
File "/Users/ereinecke/.venv/lib/python3.8/site-packages/opentimelineio/schema/marker.py", line 25, in __repr__
repr(self.media_reference),
AttributeError: 'opentimelineio._otio.Marker' object has no attribute 'media_reference'
```
Restored implementations from the pre-C++ port version and added unitests to prevent this kind of error in the future.

Fixed broken repr and str magic methods for Marker

---

docs/tutorials/write-a-hookscript.md
src/py-opentimelineio/opentimelineio/adapters/adapter.py
src/py-opentimelineio/opentimelineio/adapters/builtin_adapters.plugin_manifest.json
tests/baselines/adapter_plugin_manifest.plugin_manifest.json
tests/baselines/post_write_example.py
tests/baselines/post_write_hookscript_example.json
tests/test_hooks_plugins.py

Added support for "post_adapter_write" hooks.
Post hooks are run _after_ the file is written to disk by an adapter and passes the file path to the hooks through `_filepath` key in the `argument_map`.
Updated unit tests and added example in the hooks docs.

Implementation of post adapter write hook

---

tests/test_opentime.py

As per discussion here: #753
> My rule of thumb is that if a line of code requires a lot of careful explanation when someone new comes across it, it deserves formal documentation at the call site. So @KarthikRIyer I think a couple of sentences that explain to the next person what the test is for are in order.

Add description for faulty formatted timecode test

---

MANIFEST.in

Excludes the GitHub templates from the `MANIFEST.in` file.
This was causing `check-manifest` to fail, which in turn causes tox (And ci) to fail.

Prune the .github folder with the issue templates

---

src/opentimelineio/imageSequenceReference.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_errorStatusHandler.cpp
tests/test_image_sequence_reference.py

Updated the python errorStatusHandler to escalate details from IndexError and NotImplementedError and made ImageSequenceReference provide a more helpful exception message when trying to get a frame url from a zero rate or zero duration instance.
Split from #639, the docstring segment of that PR ended up handled elsewhere. This supersedes that PR.

Updated ErrorStatusHandler to escalate more exceptions and added detail to ImageSequenceReference exceptions

---

setup.py

Releasing OTIO beta 13, stripping the .dev1 suffix off the version in setup.py for release to pypi.

Remove .dev1 suffix for release

---

src/opentime/rationalTime.cpp
tests/test_opentime.py

Fixed issue where invalid timecode rate error message would always say `has frames beyond 0.000000` rather than the correct maximum frame number.
This error tends to come up a lot when an incorrect rate is specified when parsing a CMX edl.
Added a unittest to both ensure the `ValueError` is raised in this case and the helpful message is correctly generated.

FIxed invalid timecode frame number error message

---

src/py-opentimelineio/opentimelineio/algorithms/track_algo.py

Fixes #793
Updated doc string of `otio.algorithms.track_with_expanded_transitions()` to clarify that the returned list encapsulates the items in a transition in tuples
Please let me know if my wording is misleading or could be changed in any way.
No tests need updating for this PR

Update doc string for otio.algorithms.track_with_expanded_transitions()

---

.github/PULL_REQUEST_TEMPLATE.md

To help new people contribute to OTIO, we should ensure that they go through the proper steps. This PR adds a reminder about the CLA process to the new issue template.

Added a note about CLA requirement to PR template.

---

examples/flatten_video_tracks.py

```Fixes #811 ```
Now the example uses deepcopy when splicing the audio tracks into the output timeline.
There are no tests for the code in the `examples/` folder.

Update flatten_video_tracks.py to use deepcopy.

---

src/opentimelineio/typeRegistry.h

Fixes #822
Add underscore to the parameter names to avoid GCC's warnings about shadowing

Prefix _TypeRecord constructor params to avoid shadow warnings

---

docs/tutorials/otio-file-format-specification.md

This PR adds documentation about how metadata should be nested inside a namespace.

Document Metadata structure

---

src/py-opentimelineio/opentime-bindings/opentime_timeRange.cpp

Also re-arranged the overloaded definitions so the TimeRange/RationalTime variants would have consistent ordering.
Here is a summary of what the docstrings in python look like now:
```
|  before(...)
|      before(*args, **kwargs)
|      Overloaded function.
|
|      1. before(self: opentimelineio._opentime.TimeRange, other: opentimelineio._opentime.RationalTime, epsilon_s: float = 2.6041666666666666e-06) -> bool
|
|
|      The end of :param:`this` strictly precedes :param:`other` by a value >= :param:`epsilon_s`.
|                             other
|                               ↓
|                   [ this ]    *
|
|
|      2. before(self: opentimelineio._opentime.TimeRange, other: opentimelineio._opentime.TimeRange, epsilon_s: float = 2.6041666666666666e-06) -> bool
|
|
|      The end …
```

Added docstrings to python bindings for interval algebra methods in TimeRange

---

src/opentime/rationalTime.h
src/opentime/timeRange.h
src/py-opentimelineio/opentime-bindings/opentime_rationalTime.cpp
src/py-opentimelineio/opentime-bindings/opentime_timeRange.cpp
src/py-opentimelineio/opentimelineio/opentime.py
tests/test_opentime.py

Added duration_from_start_end_time_inclusive and range_from_start_end_time_inclusive to RationalTime and TimeRange respectively.

from_start_end_time_inclusive

---

src/opentimelineio/errorStatus.h
src/opentimelineio/serialization.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_errorStatusHandler.cpp
tests/test_serializable_object.py

```Fixes cycles in SerializableObjects cause crashes #847```
Modified the logic near #ifdef INSTANCING_SUPPORT to make use of the same table for checking for already encountered objects; however, because we only want to detect cycle and let mere instancing pass through (i.e. we don't demand things be a tree, we just demand they be acyclic) we remove an object from the table as we leave the function where we first encountered it.
In this way, we should be back to not being able to crash the system by writing bad Python code.
New tests (in tests.test_serializable_object.SerializableObjTest):
test_instancing_without_instancing_support
test_cycle_detection

detect cycles

---

CMakeLists.txt

- in the python build, shared libraries need to go along with the python
libraries because of python security policies.
- Also removes an unnecsary reference to python cmake variables in the
C++ only branch.

Revert the location of shared libraries

---

CMakeLists.txt
setup.py

Closes #885 
Refactors how the setup.py communicates target locations to the cmake so that `--prefix` and `--user` arguments are correctly handled.
*POTENTIALLY BREAKING CHANGE*: Now if installing via `pip`/`setup.py`, the C++ libraries are installed under the python install in a `cxx-sdk` instead of `cxx-libs` directory.
I'd like to note that the way of finding the _value_ of the `--prefix` argument is pretty gross. If there is a better/cleaner way, please let me know!

Support --prefix correctly in new cmake system

---

CMakeLists.txt

- Removed incorrect commas after message() type
- Use proper message type STATUS ([there is no INFO](https://cmake.org/cmake/help/v3.19/command/message.html#general-messages))
- ~Removed `D` from `${DOTIO_PYTHON_INSTALL_DIR}`~
- Replaced `:` by `=` in message text.
Colon is used for type annotation in CMake's syntax, like `-DOTIO_DEPENDENCIES_INSTALL:BOOL=OFF`

CMake: Fix message() types

---

src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py
tests/test_fcp7_xml_adapter.py

Fixed issue in FCP7 XML adapter where timecode objects without `ntsc` elements in their rate would not properly inherit the `ntsc` value from the parent context.
Most of our code was built around Premiere Pro XML files which explicitly include the `ntsc` element in their `rate` elements. XML coming from FCP 7 (maybe others) does not do this and would break the start time resolution for clips.
This may address the bug described in #830. 
The main change here is that `timecode` elements are now evaluated in the context of their parent and allow for the FCP 7 XML inheritance patterns.
To simplify code paths, I refactored some of the functions around computing a rate float from the fcp two-part `timebase` and `ntsc` elements. Very little actual logic changed, just …

FCP 7 XML: Fixed resolution of start timecode for certain NTSC rate clips

---

CMakeLists.txt

not necessary to set C++11 flags for pybind11, that's already
handled by cmake's C++ standard settings.
Signed-off-by: Nick Porcino <nporcino@pixar.com>
Each PR should link at least one issue, in the form:
https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/881
Use one line for each Issue. This allows auto-closing the related issue when the fix is merged.
Describe the reason for the change.
Add a list of changes, and note any that might need special attention during review.
If no new tests are introduced as part of this PR, note the tests that are providing coverage.

Fix Issue #881

---

README.md
src/opentimelineio/imageSequenceReference.cpp

Fixed an implicit cast that would happen between a `size_t` and an `int`.
Also addressed a line in the README.md that wasn't Python 3 safe.
closes #774
co-authored by @zebulon75018

Fix ImageSequenceReference implicit cast

---

src/opentimelineio/imageSequenceReference.cpp
tests/test_image_sequence_reference.py

Fixes #890 
There was a check to see if `target_url_base` ended in a `/` to avoid having double-/ in constructed urls. This assumed `target_url_was of at lease length 1. Added a check to not attempt the check if the length is zero.
Added test checking generation of bare filenames using `target_url_for_image_number`.

ImageSequenceReference: Added handling for empty target_url_base

---

.github/workflows/python-package.yml
Makefile
contrib/opentimelineio_contrib/adapters/tests/test_hls_playlist_adapter.py
contrib/opentimelineio_contrib/adapters/tests/tests_xges_adapter.py
setup.py
src/py-opentimelineio/opentimelineio/console/autogen_plugin_documentation.py
tests/sample_data/premiere_generators.xml
tests/test_adapter_plugin.py
tests/test_builtin_adapters.py
tests/test_cmx_3600_adapter.py
tests/test_console.py
tests/test_fcp7_xml_adapter.py
tests/test_hooks_plugins.py
tests/test_serialized_schema.py

Enables GitHub actions CI build/tests for windows and MacOS.
- CI builds for each OS and each python version (so you will now see 9 checks in the GitHub actions interface instead of 3).
- Sets Linux/3.7 as this is the only platform that computes coverage and submits coverage reports.
- Windows file handling required changing how some unit tests were working.  This was solved by adopting `tempfile.TemporaryDirectory` (native on python3, from `backports.tempfile` on python2).
- adds `backports.tempfile` as a dependency on python2 builds
- the autogen plugins script will conform paths to unix-formatting as well as being relative to the project root, to maintain consistent output across all three operating systems
- one of the test files, `premiere_generators.xml` had a "BOM" (Byte Order …

add windows and mac builds to ci

---

contrib/opentimelineio_contrib/adapters/tests/tests_xges_adapter.py
contrib/opentimelineio_contrib/adapters/xges.py
setup.py

After https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/873 was merged, this enables xges adapter tests on the same platforms/python version as other adapters.

Enable xges unit tests on all platform/python versions

---

src/py-opentimelineio/opentime-bindings/CMakeLists.txt
src/py-opentimelineio/opentimelineio-bindings/CMakeLists.txt

It turns out that we were escaping the value of `"$ORIGIN"` incorrectly in CMakeLists.txt, and this was causing an incorrect RPATH to be written into .so files on linux operating systems of "\$ORIGIN" instead of "$ORIGIN".  This fixes that escaping.

Fix escaping for ORIGIN in rpath settings

---

README.md

```Addresses #788```
Switched the last remaining mention of Travis to GitHub Actions.

Update build status badge to use GitHub Actions instead of Travis

---

src/opentime/CMakeLists.txt
src/opentimelineio/CMakeLists.txt
src/py-opentimelineio/opentime-bindings/CMakeLists.txt
src/py-opentimelineio/opentimelineio-bindings/CMakeLists.txt

This variable was incorrectly set, fixed to use the explicit name.

CMakeTexts fix: stop using the modname variable

---

CMakeLists.txt

Currently we override C++ compiler versions to c++11. This causes problems if you are building a project, c++ based, that links to opentimelineio, because non_std optional has shenanigans in it. If you build otio with 11, then try to link your project with 14, then linking will fail, because non_std will have re-routed all the optional references to std, but otio was linked with non_std optional. This change allows a build to specified consistently all the way through for the same compiler.

Don't override user supplied C++ preferences

---

src/opentime/CMakeLists.txt
src/opentimelineio/CMakeLists.txt

Create cmake alias targets for the OTIO namespace
We create and populate the necessary targets and namespace, but neglecto actually set up the alias.

Create cmake alias targets for the OTIO namespace

---

src/py-opentimelineio/opentimelineio/console/otioconvert.py
src/py-opentimelineio/opentimelineio/console/otiopluginfo.py

Adds a `--version` flag to `otiopluginfo` and `otioconvert`.  This:
- prints out the `__version__` string 
- searches for `pkg_resource` installed plugins, and prints out their dist info (which includes their version numbers)
Question for the community:  After seeing this I kind of wish there was a way to also burn the git commit hash into the repo some how.  Not sure if thats useful, but it something we could potentially do when we burn the version numbers in.
Output looks like this:
```
> otioconvert --version
OpenTimelineIO version: 0.14.0.dev1
No pkg_resource plugins installed.
```

add a --version flag to otiopluginfo + otioconvert

---

src/opentime/CMakeLists.txt
src/opentimelineio/CMakeLists.txt

```Fixes #910 ```
This branch removes the CMake `export` of the opentime and opentimelineio libraries.  In CMake, exporting generates a CMakeFile that makes the target available from the build tree to upstream projects.  An example use case is when there's a tool facilitating the build process that might also be needed by the upstream project.  However, this is not desirable from a library perspective, it would allow upstream projects to reference the library in the build folder (which is temporary) instead of the installed location (which is permanent).  See Issue for more details.
This is needed to properly link with libraries from other downstream projects, since an export will fail if its dependencies are not also exported.  Specifically, we would like to …

Avoid exporting build tree libraries

---

src/deps/CMakeLists.txt

We were adding pybind11 as a subdirectory in cmake even if the building python bindings was disabled. This PR conditionally adds pybind11.
To build the Java bindings for android we do not need the python bindings. While building for 32-bit android I was getting an error ([here](https://github.com/OpenTimelineIO/OpenTimelineIO-Java-Bindings/pull/3#issuecomment-791849975)) saying that the pybind11 cmake was looking for 32-bit python, but couldn't find it. The easy solution is to just disable building python bindings and not search for python at all. I've tested this and am able to build for 32-bit.

Add pybind11 subdirectory only if building python bindings

---

docs/index.rst
docs/tutorials/otio-env-variables.md
src/py-opentimelineio/opentimelineio/plugins/manifest.py
tests/test_plugin_detection.py

- in some cases, pkg_resources can be slow to both import and use
- adds the `OTIO_DISABLE_PKG_RESOURCE_PLUGINS` environment variable to
disable using this library for users that have those issues.
- Even for users not experiencing those issues, this speeds up the
import time of OTIO slightly.
- Also adds a new doc page with a description of OTIO environment variables.

Add an env var to disable pkg_resources

---

setup.py

bb60a6f9784b7cc05291c5df6c107a3f00f6c11f loosened the versions of packages that are required, and changed the specification of dependency versions from being exact versions to being minimum versions. However the same change was not applied to the pyaaf2 version specification. Given that pyaaf2 versions have remained backwards compatible, at least so far, it should be safe to allow users to use different versions of pyaaf2 than what is required in the setup.py currently. Therefore this change makes the version requirement of pyaaf2 also be a minimum version specification rather than an exact one.
None required.

Specify pyaaf2 requirement as a minimum version

---

.github/dependabot.yml

Dependabot requires an "interval" property in its yaml file.  I missed that last time, whoops.

add interval field to dependabot yaml

---

src/py-opentimelineio/opentimelineio/adapters/file_bundle_utils.py

Fixes: 
https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/938
Removed non-ascii char to allow python parsing

Removed inadvertent unicode char

---

contrib/opentimelineio_contrib/adapters/extern_rv.py
contrib/opentimelineio_contrib/adapters/rv.py

Originally OTIO was a dependency free python library.  Over time, we've made OTIO into a C++ backed thing and can no longer guarantee that the library is compatible across the RV barrier.  This shifts the RV adapter around so that a simplfied manifest json is handed across to a small script inside RV that can run the RV commands.

RV adapter fix: don't require having access to OTIO from python interpreter in rv

---

src/py-opentimelineio/opentimelineio/adapters/cmx_3600.py
src/py-opentimelineio/opentimelineio/adapters/file_bundle_utils.py

Found an additional non-ascii character in a doc string related to a citation.

Ascii doc fix

---

setup.py

Fixes #813
Each PR should link at least one issue, in the form:
```Fixes #823```
Use one line for each Issue. This allows auto-closing the related issue when the fix is merged.
Added the pybind11 smart tool to find python: https://pybind11.readthedocs.io/en/latest/compiling.html#findpython-mode
On windows: `/path/to/blender/python -m pip install` wasn't working.

Use Pybind11's find python tool to correctly locate python install information

---

tests/test_plugin_detection.py

The test_plugin_detection test was failing for me in python 2.7 due to a missing `importlib.reload()`. I believe this is only available in python 3.4+. 
This change lets the test fall back to `imp.reload()` in cases where it can't find the `importlib` one. 
There is a related question about how the 2.7 tests did not detect this which I think is related to a missing `mock` module. I'll follow up offline about that.

Allow test to run in both python 2.7 and python 3.3+ wrt reloading modules

---

.github/workflows/python-package.yml

Our CI builds do not have the `mock` module installed, so not all unit tests are running for python 2.7.  This installs that library for python2.7 builds only to ensure that all the tests are running.

install mock on CI builds for python 2.7

---

docs/tutorials/otio-serialized-schema.md
src/py-opentimelineio/opentimelineio/plugins/manifest.py
tests/test_adapter_plugin.py
tests/test_plugin_detection.py

- During plugin loading, checks to see which source_files have already been loaded before loading a new plugin.
- For pkg_resource plugins that use the function approach rather than the manifest.json approach, generates a source_files path based on the path to the module containing the function.
- Adds unit tests to check duplicate entries.
- Also updates and clarifies some documentation around how the plugin manifests are loaded.

Only load a manifest if it has not been loaded

---

src/opentimelineio/timeline.cpp
src/opentimelineio/timeline.h
tests/test_timeline.py

By David Baraff. Supercedes https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/852 which had rebasing issues.
Fixes Timeline::set_tracks(nullptr) leads to bad state #851
Summarize your change.
Sets _tracks to a new Stack() if the incoming pointer is null
Reference associated tests.
Added a new test in test_tracks_set_null_tracks in tests/test_timeline.py

make Timeline::set_tracks(null_ptr) create a new Stack to fix crash

---

.github/workflows/python-package.yml

Closes #970 
Looks like there is a specific interaction of codecov & dependabot.  This PR turns off uploading coverage from dependabot runs (which we probably did not want code coverage checks on anyway).

do not upload code coverage statistics if the PR is opened by dependabot

---

setup.py

Link the Issue(s) this Pull Request is related to.
Fixes #984
Summarize your change.
This is an attempt to fix building when multiple python versions are installed. Currently, the `PYBIND11_FINDPYTHON` will cause pybind to attempt to locate the version of python to use when generating the python bindings. The problem with this is that is may not match the version of python where the files will be installed. From my experimentation, it seems the FINDPYTHON option will search the PATH and take the first match to find python. Whereas setup.py will build the installation for the version of python that invoked it.
If these versions don't match, the python bindings will be built for a different version of python in which they are used and loading the resulting libraries will fail.
To fix it, we …

Force pybind to use same python as otio

---

examples/CMakeLists.txt
examples/conform.cpp
examples/conform.py
examples/flatten_video_tracks.cpp
examples/python_adapters_child_process.cpp
examples/python_adapters_embed.cpp
examples/summarize_timing.cpp
examples/util.cpp
examples/util.h

```Fixes #994```
This PR adds a C++ version of the conform.py example. The code is mostly identical to the Python version except for the ```argparse``` command line parsing which doesn't have an equivalent in C++.
There are also a couple minor fixes to other example files, I can break those out into a separate PR if necessary. Specifically conform.py had some syntax errors with my Python 3 setup, hopefully the changes I made are also compatible with Python 2. It might be worthwhile to add the examples to the CI at some point...

Cxx conform example

---

CMakeLists.txt
setup.py
src/deps/CMakeLists.txt
src/opentime/CMakeLists.txt
src/opentimelineio/CMakeLists.txt

```Fixes #666 ```
```Fixes #771  ```
This branch fixes building issues, both for building wheels and building with third-party projects.  In my particular case (#771) it allows building with Imath. 
The problem with the current setup is that it does not allow building with any sub-projects that use the standard `CMAKE_INSTALL_INCLUDEDIR` variable.  These are not be able to correctly install, since the `setup.py` effectively sets this variable to the build directory which generates the following error (in the case of Imath when compiled on Windows):
```
CMake Error in src/deps/Imath/config/CMakeLists.txt:
Target "ImathConfig" INTERFACE_INCLUDE_DIRECTORIES property contains path:
"C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-wwijcqv7\build\lib.win-amd64-3. …
```

Remove CXX sdk in Python site-packages

---

.clang-format
MANIFEST.in

Closes #706 
I've added a clang format file. This is the one from openEXR with a tiny change. The space before parentheses has been removed.
I'd also like to propose to disable brace wrapping after these declarations (these wrappinngs aren't present in the code currently so disabling them should be comfortable):
- class
- control-statement
- enum
- function
- namespace
- struct
- union
- extern block
Any thoughts or additional changes you'd like to propose?
If everyone agrees then I'll reformat the files and update the PR.
@jminor @meshula @ssteinbach @reinecke

Add .clang-format file

---

Makefile

Closes #1021 
The `make format` target applies the clang format to the C++ code.

Add target make format

---

src/opentime/rationalTime.cpp

```Fixes #1033```
This PR fixes a couple warnings from gcc 10.3:
```
warning: catching polymorphic type ‘class std::exception’ by value [-Wcatch-value=]
```

Use const references when catching exceptions

---

docs/tutorials/otio-plugins.md
src/py-opentimelineio/opentimelineio/adapters/builtin_adapters.plugin_manifest.json
src/py-opentimelineio/opentimelineio/adapters/svg.py
tests/sample_data/multiple_track.otio
tests/sample_data/multiple_track.svg
tests/sample_data/simple_cut.otio
tests/sample_data/simple_cut.svg
tests/sample_data/transition.otio
tests/sample_data/transition.svg
tests/test_svg_adapter.py

Closes #519
Squashed version of #649

Implement OTIO to SVG adapter

---

.gitattributes

Adds a [linguist override](https://github.com/github/linguist/blob/master/docs/overrides.md) to syntax highlight `.otio` files as JSON.

Added linguist override to detect .otio files for JSON highlighting

---

docs/tutorials/architecture.md
docs/tutorials/write-a-media-linker.md
docs/tutorials/write-an-adapter.md

- otio.media_reference -> otio.schema
- updated the text of an exception to match the current text

update outdated python module paths in docs

---

src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp

Relates to issue #828
I've been working on building wheels for Python 3.9 and I've been blocked by an issue where `opentimelineio` couldn't be imported once compiled. The issue only happened on Windows with Python 3.9 when the extension was statically linked (which is the default).
After a lot of back and forth and getting some help from @meshula and @LazyDodo, I was able to finally fix the problem.
The issue would manifest itself like this:
```
>>> import opentimelineio
File "<stdin>", line 2, in <module>
File "C:\Users\jeanchristophemorin1\AppData\Roaming\Python\Python39\site-packages\opentimelineio\__init__.py", line 35, in <module>
from . import (
File "C:\Users\jeanchristophemorin1\AppData\Roaming\Python\Python39\site-packages\opentimelineio\exceptio …
```

Fix failing import of opentimelineio in Python 3.9 on Windows

---

CMakeLists.txt

Small fix to remove an annoying CMake warning in build logs. See https://github.com/PixarAnimationStudios/OpenTimelineIO/runs/3642334378?check_suite_focus=true#step:8:523 for the wanring in context.
The warning in question is:
```
CMake Warning (dev) at src/py-opentimelineio/opentimelineio-bindings/cmake_install.cmake:80 (list):
Syntax error in cmake code at
D:/a/OpenTimelineIO/OpenTimelineIO/build/src/py-opentimelineio/opentimelineio-bindings/cmake_install.cmake:81
when parsing string
C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-3xa3dntx\build\lib.win-amd64-3.7\/bin/
Invalid escape sequence \U
Policy CMP0010 is not set: Bad variable reference syntax is an error.  Run
"cmake --help-policy CMP0010" for policy details.  Use the cmake_policy
command to set the policy and suppress this …
```

Fix CMP0010 CMake warning caused by back slashes on Windows

---

.github/workflows/python-package.yml
CMakeLists.txt
setup.py

Fixes #667 .
**Summary**
This PR makes it possible to build wheels on Windows in GitHub Actions.
I also updated cibuildwheel from 1.10.0 to 1.12.0 (the last version compatible with Python 2.7) and I'm now using the GitHub Action `pypa/cibuildwheel@v1.12.0` instead of installing cibuildwheel manually.
Wheels have been uploaded to test.pypi.org and can be installed using:
```
python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple opentimelineio==0.14.0dev1
```
where `python` is the interpreter you want to install the package into.
We would be extremely happy if we can get some people to test them, specially the Blender community woking on Windows. You can comment in this PR if you find any issues and you can even comment if it works :) …

Create wheels on Windows

---

.github/workflows/python-package.yml
README.md
setup.py

Fixes #828.
Add support for Python 3.9.
I also took the occasion to set the `python_requires` to explicitly set the supported Python versions and prohibit Python 3.9.0. Additionally I removed the logic around the install requires for Python < 3 to use a more modern and static method.

Support Python 3.9

---

Makefile

Fixes #1005
**Summary**
Adds a `wheel` target to the Makefile.
Running `make wheel` will build a `.whl` package for the available python version to the root of the project.
Running `make clean` will remove all `*.whl` files from the project root.

Make target for building wheel

---

Makefile

Fix #1078 
Also tunes the logic in the target to use wildcards.  I'm considering tuning the style file itself, and maybe even adding in a post-formatted version of the code to this PR as well.

Makefile "format" target tuning

---

docs/_static/spatial_coords_example1.svg
docs/_static/spatial_coords_example2.svg
docs/_static/spatial_coords_example3.svg
docs/_static/spatial_coords_example4.svg
docs/_static/spatial_coords_system.svg
docs/tutorials/spatial-coordinates.md

Fixes #1011
**Summary**
This PR contains a draft version of the documentation written for the
Coordinate System proposal for OpenTimelineIO.
The following PR contains the actual implementation : https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/998
I used markdown for the whole documentation and SVG for graphics. I originally had built the graphics using draw.io but I thought having them as stand-alone SVGs would be more useful and lightweight.
I tried using recursive SVGs (ie.: invoke an SVG file from another SVG file through an `image` tag) to avoid code duplication, but apparently when an SVG is used as image, it must be complete in a single file. If anyone has a simple solution to this, let me know.
**Files Changed**
docs/tutorials/spatial-coordinates.md
-The actual …

Add spatial coords doc draft

---

docs/tutorials/spatial-coordinates.md

```Fixes #771```
docs/tutorials/spatial-coordinates.md : Used `available_image_bounds` instead of `bounds` and removed the `Bounds.1` schema. Also removed `metadata` since Bounds is no longer a `SeralizedObjectWithMetadata`.
No tests required, just a documentation update.

Updated spatial coordinates doc : available_image_bounds.

---

contrib/opentimelineio_contrib/application_plugins/tests/test_rv_reader.py

Fixes #1146 
The tests for the RV plugin will always fail when they are run.  This is because the setup creates three clips with a duration of RationalTime(30,24) and the test is expecting new clips at RV global frames 1, 20, and 40.  
To fix the issue, I just lowered the duration to RationalTime(3,24) and check for clips at RV global frames 1, 4 and 7. 
Only the modified test: test_rv_reader.py

Fix RV plugin test timing

---

.github/workflows/python-package.yml

This PR fixes the sdist that is uploaded to PyPI.
The problem was reported in https://app.slack.com/client/TKA297NS0/CMQ9J4BQC.
The issue was simply that I forgot to tell GHA to recursively clone and checkout the submodules.
I tested locally by downloading the GHA artifact from my fork and installed the sdist.

Update sdist to include submodules

---

.github/workflows/python-package.yml

This is a cherry-pick of #1152 for a 0.14 patch release.
See the slack discussion around [this message](https://academysoftwarefdn.slack.com/archives/CMQ9J4BQC/p1637282298263800) for more context.

Recursively get submodules before generating the sdist

---

docs/tutorials/quickstart.md

As note in https://academysoftwarefdn.slack.com/archives/CMQ9J4BQC/p1636760978147000, the developer quickstart documentation is out of date right now.
This PR removes obsolete instructions, adds some more instructions and also use modern methodologies (e.g. call `python -m pip` install of `pip`, don't call `python setup.py`, etc).
Hopefully it should be clear enough and the additions I made will help future contributors.

Improve the developer quickstart documentation

---

setup.py

Removed `.dev1` from version number to prepare for release

Remove .dev1 from version

---

CMakeLists.txt
CONTRIBUTING.md
contrib/opentimelineio_contrib/adapters/tests/sample_data/no_metadata.otio
contrib/opentimelineio_contrib/adapters/tests/sample_data/not_aaf.otio
contrib/opentimelineio_contrib/adapters/tests/sample_data/rv_metadata.otio
contrib/opentimelineio_contrib/adapters/tests/sample_data/rv_metadata.rv
contrib/opentimelineio_contrib/application_plugins/rv/example_otio_reader/PACKAGE
docs/tutorials/contributing.md
docs/use-cases/conform-new-renders-into-cut.md
examples/sample_plugin/setup.py
setup.py
src/py-opentimelineio/opentimelineio/__init__.py
src/py-opentimelineio/opentimelineio/console/__init__.py
tests/baselines/plugin_module/otio_jsonplugin.egg-info/PKG-INFO
tests/baselines/plugin_module/otio_mockplugin.egg-info/PKG-INFO

This PR removes some, but not all, of the mentions of Pixar from the repo, as part of our prep for transitioning the project to ASWF ownership.

Prep for ASWF transfer

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
docs/tutorials/contributing.md

In preparation for transfer of OpenTimelineIO from Pixar to ASWF, we are changing the contact email addresses to the OTIO TSC private mailing list.

Replaced @pixar email addresses with @aswf email addresses.

---

tests/test_console.py

Tests on Windows were failing as the test code uses the Unix command `which`. Here we change that to use a platform specific command (`where`) when running on Windows. `shutil.which()` cannot be used as it's Python3.3+ only.
I should also say I don't have a Linux machine to test on so this has only been tested on Windows.

Use platform specific command to find path

---

.github/workflows/python-package.yml

I recently noticed that the code coverage report uploads were no more running. The cause was that we forgot to un-bake the `GH_COV_OS` in the workflow after we release 0.14.0.

Fix code coverage report uploads

---

src/py-opentimelineio/opentime-bindings/opentime_rationalTime.cpp

I noticed while working on the docs for the Python bindings that the code base had a reference to a deprecated Pybind11 method, `get_type`. As stated in https://pybind11.readthedocs.io/en/stable/upgrade.html#v2-6, the replacement is `py::type::of`.
Quote from the doc:
> The undocumented h.get_type() method has been deprecated and replaced by py::type::of(h).
This PR replaces the `get_type` call with `py::type::of`.

Replace deprecated Pybind11 get_type() usages by py::type::of()

---

src/py-opentimelineio/opentimelineio/adapters/svg.py

Apologies for the delay. I haven't been keeping well for a while.
#1177
- The SVG Adapter erroneously assumed media_reference always has target_url. Eg. GeneratorReference does not have target_url. I've added a check for the attribute before drawing it.
- The adapter failed with timelines with transitions at the end of a track. Added a fix for that.

SVG adapter fixes

---

contrib/opentimelineio_contrib/application_plugins/rv/example_otio_reader/otio_reader.py
contrib/opentimelineio_contrib/application_plugins/tests/test_rv_reader.py
tests/test_clip.py
tests/test_composition.py

Fixes #1089 
This branch adds support for reading the `available_image_bounds` in the RV OTIO import plugin. 
This works by creating a `RvTransform2D` node for each media_reference we find that has `available_image_bounds` set.  RV uses scale/translate properties on its 2D transforms, we use the difference between the max and the min vectors of the box (ie the size) to set the scale and the center of the box to set the translate.  The x-scale is scaled by the inverse aspect ratio since in RV a scale of 1.0 means the media will be drawn according to the aspect ratio.
Since RV uses a coordinate system equivalent to an OTIO `Box2d(min=(-0.5, -0.5), max=(0.5, 0.5))` and the incoming OTIO may be in a different coordinate system we calculate a global normalization …

Support available_image_bounds in the "Example OTIO Reader" RV plugin

---

src/py-opentimelineio/opentime-bindings/opentime_rationalTime.cpp

I noticed that the `RationalTime.__copy__` method had an argument that is not used. The `__copy__` special method is not supposed to accept arguments.
From https://docs.python.org/3/library/copy.html:
> In order for a class to define its own copy implementation, it can define special methods \_\_copy\_\_() and \_\_deepcopy\_\_(). __The former is called to implement the shallow copy operation; no additional arguments are passed__. The latter is called to implement the deep copy operation; it is passed one argument, the memo dictionary.

Remove extra useless parameter from RationalTime.__copy__ method

---

docs/tutorials/adapters.md

Fixes #1201 
Updated URLs of the PDFs to the new location on static.amwa.tv

Update AAF Documentation Link

---

src/py-opentimelineio/opentime-bindings/opentime_timeTransform.cpp
tests/test_opentime.py

`TimeTransform.__deepcopy__` was missing the `memo` keyword argument, which is required.
Without this change, `copy.deepcopy` raises an exception:
```
>>> import copy
>>> import opentimelineio.opentime
>>> rt = opentimelineio.opentime.RationalTime(12, 25)
>>> tt = opentimelineio.opentime.TimeTransform(rt)
>>> 
>>> copy.deepcopy(tt)
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.10/copy.py", line 153, in deepcopy
y = copier(memo)
TypeError: __deepcopy__(): incompatible function arguments. The following argument types are supported:
1. (self: opentimelineio._opentime.TimeTransform) -> opentimelineio._opentime.TimeTransform
Invoked with: otio.opentime.TimeTransform(offset=otio.opentime.RationalTime(value=12, rate=25), scale=1, rate=-1), {}
```

Add missing memo keyword argument to TimeTransform.__deepcopy__ method

---

contrib/opentimelineio_contrib/adapters/kdenlive.py

Fixes #1159
Fixes #1160
Don't rely anymore on old "global_feed" attribute to identify main tractor, but check last tractor in xml is the top one.

Kdenlive adapter: process recent project format

---

CMakeLists.txt

On macOS, we now build libopentime and libopentimelineio as universal (both arm64 and x86_64)

On macOS build universal arm64 and x86_64

---

docs/tutorials/quickstart.md
setup.py
src/opentimelineview/console.py
src/opentimelineview/details_widget.py
src/opentimelineview/ruler_widget.py
src/opentimelineview/timeline_widget.py
src/opentimelineview/track_widgets.py

Fixes #1215
Fixes #1220
This PR upgrades opentimelineview to work with PySide6. I believe most of these changes are also compatible with PySide2 except for these:
* from PySide6
* QtGui.QAction
I'm not very familiar with Python so I'm not sure if there is a way to support both PySide2 and PySide6?
A screenshot of otioview running with PySide6 on an Apple M1:

Port to PySide6

---

tests/utils.h

Fixes #1235
This branch undefines NDEBUG when using unit tests.  This is to ensure the asserts used in assertEqual and assertNotEqual, etc fail the test even in release builds.  Since this file is only included by the unit tests it won't have any impact outside of that scope.
test_clip.cpp and test_opentime.cpp

Don't skip asserts in unit test release builds

---

src/opentimelineview/console.py
src/opentimelineview/timeline_widget.py
src/opentimelineview/track_widgets.py

Fixes #1207 
This resolves an issue where `otioview` didn't take into account `TrackNameItem` width when framing the timeline within the current graphics scene. This resulted in track ends going offscreen without the ability to scroll to them until the window was expanded. It will now factor in the largest name item width to adapt to normal and expanded item states.
This PR also resolves a related issue with the initial size and position of the `otioview` window. Previously the window was centered to a default constructed `QScreen`, which in my debugging on Windows could contain garbage size data and put the otioview window far off screen. It also didn't take into account small screens (like the laptop I am contributing from), window title bars, and OS-used portions of the screen for …

otioview track and window fit improvements

---

CMakeLists.txt
src/py-opentimelineio/CMakeLists.txt

Currently when setting `OTIO_PYTHON_INSTALL=ON` in CMake, only the compiled Python bindings are installed, which can't be used on their own. This update expands this to match the OTIO PyPI package in the CMake install location, including the three pure-python libs: `opentimelineio`, `opentimelineview`, and `opentielineio_contrib`. The result is that the CMake install is production-ready in a Python env.
While on by default when building the Python bindings, `opentimelineview` is also gated behind the existing (and currently unused) `OTIO_INSTALL_COMMANDLINE_TOOLS`, and `opentielineio_contrib` behind a new `OTIO_INSTALL_CONTRIB` option, so both can be turned off if only the core lib is needed.

Install full OTIO Python env with CMake

---

src/opentime/rationalTime.h

This PR fixes an issue raised by the version of Clang bundled with XCode 13.x, see below. Clang correctly notices that constexpr can't be used on a mutating function.
````
Users/nporcino/build/local/include/opentime/rationalTime.h:160:20: error: cannot assign to non-static data member within const member function 'operator+='
_value = other._value + value_rescaled_to(other._rate);
~~~~~~ ^
/Users/nporcino/build/local/include/opentime/rationalTime.h:156:35: note: member function 'opentime::v1_0::RationalTime::operator+=' is declared const here
constexpr RationalTime const& operator+=(RationalTime other) noexcept
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/nporcino/build/local/include/opentime/rationalTime.h:161:20: error: cannot assign to non-static data …
```

clang notices that constexpr can't be used on a mutating function

---

contrib/opentimelineio_contrib/adapters/advanced_authoring_format.py

When we describe our AAF into OTIO space, we apply the following heuristic:
1) First look for top level mobs and if found use that to transcribe.
2) If we don't have top level mobs, look for composition mobs and use them to
transcribe.
3) Lastly if we don't have either, try to use master mobs to transcribe.
If we don't find any Mobs, just tell the user and do transcrption on an empty
list (to generate some 'empty-level' OTIO structure)
This heuristic is based on 'real-world' examples. There may still be some
corner cases / open questions (like could there be metadata on both
a composition mob and master mob? And if so, who would 'win'?)
In any way, this heuristic satisfies the current set of AAFs we are using
in our test-environment.

AAF Adapter: Mob transcription heuristics

---

contrib/opentimelineio_contrib/adapters/ale.py

This gives caller an option to specify which column to use as a clip’s name.

Add ALE adapter argument `ale_name_column_key`

---

src/py-opentimelineio/opentimelineio/plugins/manifest.py
tests/test_adapter_plugin.py

This restores the ability to set OTIO_PLUGIN_MANIFEST_PATH to an empty string
to indicate no local custom manifest file.
Fixes #1252
This changes a truthy check on the env var OTIO_PLUGIN_MANIFEST_PATH to skip any false value and not explicitly `is None`. This will allow OTIO_PLUGIN_MANIFEST_PATH='' to be equivalent to that env var not being set. 
Added a test specifically for this. Also updated all tests in `test_adapter_plugin.py` to always un-set custom env vars or manifests on exceptions due to test failures so as to not pollute subsequent tests.

Support OTIO_PLUGIN_MANIFEST_PATH being set to an empty string

---

.github/workflows/python-package.yml
README.md
setup.py

Fixes #1224.
Add official support for Python 3.10.
Note that I had to update `cibuildwheel` to the latest because 1.12.0 doesn't support Python 3.10. And while being there, I also made sure to use the latest for all Python versions except Python 2.7. You will also notice that I force `manulinux2010` on Linux. This is because this is the version that was previously used and the latest cibuildwheel defaults to manulinux2014. It's important to stick to manylinux2010 because of the VFX platform. See https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/1094 for more details.
I invite anyone interested to test to download the wheels artifact from the job and test locally on your machine.
If anyone is curious, it's a pretty big feat to be able to support 2.7 and 3.10 at the same time …

Add Python 3.10 to CI

---

src/py-opentimelineio/opentimelineio/schema/clip.py
tests/test_clip.py

```Fixes #1257```
Pull #926 removed each_clip inadvertently from Clip. This change reintroduces it.

Fix #1257 missing each_clip on Clip

---

CMakeLists.txt
src/deps/CMakeLists.txt
src/opentimelineio/CMakeLists.txt

With this change, OpenTimelineIO will (1) detect VFX platform 2022, attempt to fall back to 2021 or earlier, then fall back to a locally cloned copy of Imath in src/deps.
The reason for this change is that OpenTimelineIO should use an Imath in the system already so that it is API compatible when both OpenEXR and OpenTImelineIO are used in the same project.
There is no extra logic to override install vfxplatform variants, as this can be accomplished in the usual manner by passing variables through the command line for cmake's find_package library to consume.
Fixes #1254

Detect & use Imath from vfxplatform CY2019-2022

---

contrib/opentimelineio_contrib/adapters/extern_rv.py
contrib/opentimelineio_contrib/adapters/rv.py
contrib/opentimelineio_contrib/adapters/tests/test_rvsession.py

This can be used with rv versions that support python 3
Fixes #1264
The rv_session adapter was written in a time before any version of rv supported python 3. That's now a supported version of python so this change enables python 3 for this adapter.
Add a list of changes, and note any that might need special attention during review.
There was one issue with testing where the connections list was not stable between python versions. I think this is due to dict order differences used in the rvSession.py's nodes dict.

Support python 3 in the "rv_session" adapter.

---

tests/test_v2d.py

This is to support both imath 2 and 3
As part of vfxreference platform support and imath 2, we need to check for either `ValueError` or `RuntimeError` as the exception type changes.

Update test_v2d to support multiple exception types

---

contrib/opentimelineio_contrib/adapters/advanced_authoring_format.py
contrib/opentimelineio_contrib/adapters/tests/test_aaf_adapter.py
tests/test_item.py

An extension of the AAF clip enabled/muting process, start in #1212
This covers the currently known cases of how clip mutes are being handled in the AAF, and the adjacent logic for the closely related scenarios of `ScopeReferece` objects, and multi-cam clip objects.
@jminor In updating/running the tests for this, it looks like the test AAF file is actually not correct for this. If the `Selected` attribute in the `Selector` object is a `ScopeReference`, as it is in that test file, I don't believe that specifically means the clip is muted. In all situations I've seen, where the clip is muted, the `Selected` attribute should be a `Filler` object. 
Is there anyone else who can weigh in on this? Looking at the AAF documentation, there's no mention of the `ScopeReference` specifically saying …

AAF Clip Enabled/Muting Update

---

maintainers/verify_license.py

This PR updates the maintainers/verify_license.py script to support Swift, C and Objective-C++ source files so that it can be used on the OTIO language binding repos.

Updated verify_license.py to support more languages

---

src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py

Fixes #839 
- Added in the FCPXML Writer an empty subtag `<format />` after `<media><video>` to satisfy Resolve's requirements.
Tested resulting XML: imports fine in Resolve and Premiere.
Before fix, tested the following files, all would show up as a black clip in Resolve.
```
otioconvert -i tests/sample_data/big_int.otio -o ~/otio_fix/big_int.xml               
otioconvert -i tests/sample_data/cdl.edl -o ~/otio_fix/cdl.xml                   
otioconvert -i tests/sample_data/dissolve_test_2.edl -o ~/otio_fix/dissolve_test_2.xml
otioconvert -i tests/sample_data/enabled.otio -o ~/otio_fix/enabled.xml               
otioconvert -i tests/sample_data/multiple_track.otio -o ~/otio_fix/multiple_track.xml
```
After fix, same files as above provide a valid Resolve timeline and continue to be able …

fix #839 - FCP XML outputs not recognized by Resolve

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
docs/tutorials/adapters.md
docs/tutorials/architecture.md
docs/tutorials/contributing.md
docs/tutorials/quickstart.md
docs/use-cases/animation-shot-frame-ranges.md
docs/use-cases/shots-added-removed-from-cut.md
maintainers/download_gha_artifact.py
maintainers/fetch_contributors.py
setup.py
src/py-opentimelineio/opentimelineio/adapters/cmx_3600.py

OTIO has moved to the AcademySoftwareFoundation GitHub org. This PR updates all links that pointed to the old repo.

Updated URLs to new AcademySofwareFoundation GitHub org.

---

src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp

This PR fixes #1188.
The argument `effect` in the Gap constructor has been changed to `effects`.

Fixes #1188 BREAKING CHANGE: change "effect" argument to Gap constructor to "effects"

---

src/py-opentimelineio/opentimelineio-bindings/otio_imath.cpp

This PR fixes an issue reported in Slack (see https://academysoftwarefdn.slack.com/archives/CMQ9J4BQC/p1654121088621319).
The issue in question is that importing OpenTImelineIO in Katana would raise an import error like `ImportError: generic_type: type "V2d" is already registered!`.
The issue comes from the fact that Katana ships Python bindings for Imath made with Pybind11 and OTIO also provides parts of Imath using Pybind11.
The solution to this problem is to make the classes provided by OTIO module-local (see https://pybind11.readthedocs.io/en/stable/advanced/classes.html#module-local-class-bindings).
To quote the documentation:
>When creating a binding for a class, pybind11 by default makes that binding “global” across modules. What this means is that a type defined in one module can …

Use py::module_local() for Imath bindings

---

src/py-opentimelineio/opentimelineio-bindings/otio_errorStatusHandler.cpp
tests/test_core.py

Fixes #1307.
This PR modifies the IO exceptions raised when using serializing and de-serializing functions from the bindings.
Previously the exceptions raised were of type `ValueError`. With this change, the error type is determined based on `errno`. Which means it will now raise the same exceptions as the built-in python IO functions.
I also added unit tests to make sure the changes are indeed working and to get coverage in an area that wasn't covered before. The tests also show different exception types being raised.
Using @reinecke 's example:
```
>>> opentimelineio.adapters.read_from_file("/tmp/doesnotexist.otio")
File "<stdin>", line 1, in <module>
File "/home/jcmorin/jcmenv/aswf/OpenTimelineIO/.venv/lib/python3.10/site-pac …
```

Python bindings: raise proper exceptions for IO operations

---

src/opentimelineview/ruler_widget.py

When working on an adapter I found this potential divide by zero error, causing nothing to show up at all in the timeline viewer.

Prevent divide by zero and print warning if width is zero

---

.github/workflows/python-package.yml

This PR adds a concurrency group to the builds so that only one build for a branch can run at the same time. When pushing a new commit on a branch and a job is already running on that branch, the build will be cancelled to allow to build the new commit.
That's becoming more important now that we have DCO in place. It's quite easy to forget to sign-off a commit and have to rebase commits. That would trigger "useless" builds.
This PR fixes that problem.
The concurrency group is per workflow + branch WHIch means builds on other branches won't be affected.
As an example, I initially pushed without signing my commit, then had to sign + push again. That triggered two builds. The first one (https://github.com/AcademySoftwareFoundation/OpenTimelineIO/actions/runs/2521514987) as automatically …

Cancel in-progress CI jobs for the same branch

---

MANIFEST.in
setup.py

Fix setuptools deprecation warnings related to importable files considered as data files. Such a warning can be seen at https://github.com/AcademySoftwareFoundation/OpenTimelineIO/runs/6563968215?check_suite_focus=true#step:8:414.
```
/tmp/pip-build-env-tkhu7fyq/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py:153: SetuptoolsDeprecationWarning:     Installing 'opentimelineio_contrib.application_plugins.rv.example_otio_reader' as data is deprecated, please list it in `packages`.
!!
############################
############################
Python recognizes 'opentimelineio_contrib.application_plugins.rv.example_otio_reader' as an importable package, however it is
included in the distribution as "data".
This behavior is likely to change in future versions of setuptools …
```

Fix setuptools deprecation warnings

---

tests/test_clip.py
tests/test_effect.py
tests/test_item.py
tests/test_transition.py

This pull request should keep all the coverage lost if #1348 was merged

Add unit tests in preparation for moving the aaf adapter

---

tests/test_otiod.py
tests/test_otioz.py

I noticed these file handles were leaking when running tests on mingw64.  
I matched the style that's in the files, but I think it would be better to use a `TemporaryDirectory` and cleanup when the test is done.  Some tests are doing that, but it is a bit mixed.

Close Temporary file handles in tests

---

examples/shot_detect.py

The python bytes vs str issue is present in the `shot_detect.py` example.  This should fix that and make it usable again.

Python3 fixes for the shot_detect example

---

contrib/README.md
docs/tutorials/write-an-adapter.md

Adds a README.md to the contrib area to explain the break-out process in-progress.

Added documentation explaining contrib and outlining process around it

---

src/py-opentimelineio/opentimelineio/plugins/manifest.py
tests/baselines/plugin_module/otio_override_adapter.egg-info/PKG-INFO
tests/baselines/plugin_module/otio_override_adapter.egg-info/entry_points.txt
tests/baselines/plugin_module/otio_override_adapter/plugin_manifest.json
tests/test_plugin_detection.py

This pull request is meant to assist the moving contrib adapters to external repos.  
You can use `$OTIO_PLUGIN_MANIFEST_PATH` to override a contrib adapter, however this can be inflexible and difficult to test your adapter when you install it.
Being able to use a stock install of OTIO also means you don't have to manage pull requests for 2 repos at the same time when starting to move a contrib adapter.
This issue has been mentioned in https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1348

Load entrypoint plugins before builtin and contrib.

---

src/opentime/rationalTime.cpp
src/opentime/rationalTime.h
tests/test_opentime.cpp
tests/test_opentime.py

#1293
@jchen9 Hi Julian, here's a rework of the existing routine to address the problem you found, and introduce a little more rigor to what is or is not a well-formed time string.
```Fixes #1293```
Describe the reason for the change.
- fixes parsing of time strings without leading zeroes.
- enforces that a negative sign can only appear in the left most position
- implementation does not allocate memory or copy strings
- implementation does not allow exponential notation and other things that std does allow but are inappropriate for time strings
-  compatible with strings produced by ffprobe
adds C based tests corresponding to the existing Python based tests.

Fix parsing of time_strings lacking leading zeroes

---

.github/workflows/python-package.yml
setup.py
tests/test_plugin_detection.py
tests/test_url_conversions.py

This is the minimal amount of changes required to add mingw_x86_64 support on windows and pass all the tests.
This pull request is mainly for discussion as to if this is a platform OTIO wishes to support. I haven't looked into adding the platform to CI yet, but feels like it might be a bit of a headache to get working. 
I also haven't been able to get it to build in 32-bit mode yet, just in 64-bit.
Not being able to build on mingw has been mentioned here https://github.com/AcademySoftwareFoundation/OpenTimelineIO/discussions/1342#discussioncomment-3088730

Add basic mingw_x86_64 build support

---

src/opentimelineio/serializableCollection.h
src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp
src/py-opentimelineio/opentimelineio/schema/serializable_collection.py
src/py-opentimelineio/opentimelineio/schema/stack.py
src/py-opentimelineio/opentimelineio/schema/timeline.py
src/py-opentimelineio/opentimelineio/schema/track.py
tests/CMakeLists.txt
tests/test_clip.cpp
tests/test_serializableCollection.cpp
tests/test_serializable_collection.py
tests/test_timeline.cpp
tests/test_timeline.py
tests/test_track.cpp
tests/test_track.py

Signed-off-by: Darby Johnston <darbyjohnston@yahoo.com>
Fixes #1400
Fixes an issue where SerializableCollection::children_if doesn't recurse into timelines. I'm marking this as a draft for now since it doesn't address all of the items in the issue (Python tests and missing arguments).

Fix for SerializableCollection::children_if

---

src/opentime/rationalTime.cpp
src/opentimelineio/serialization.cpp

Signed-off-by: Darby Johnston <darbyjohnston@yahoo.com>
Fixes #1413

Fix compiler warnings on Windows

---

src/opentimelineio/errorStatus.cpp
src/opentimelineio/serializableObject.h
src/opentimelineview/timeline_widget.py
src/py-opentimelineio/opentimelineio-bindings/otio_anyVector.h
src/py-opentimelineio/opentimelineio-bindings/otio_imath.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_utils.cpp
src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py
src/py-opentimelineio/opentimelineio/hooks.py
src/py-opentimelineio/opentimelineio/plugins/manifest.py
src/py-opentimelineio/opentimelineio/schema/track.py
src/py-opentimelineio/opentimelineio/url_utils.py

Here are a few typos and cosmetics fixes I noticed when reading though the code.

Fix a few typos and cosmetics inconsistencies

---

CMakeLists.txt
MANIFEST.in

There were a few more places in the CMake/Manifest.in that were referencing travis, this should remove them.
**for landing in beta 16**

Remove Travis traces

---

.github/workflows/python-package.yml

Left over from #1418, remove cp27 build step

remove cp27 builds from CI

---

contrib/opentimelineio_contrib/adapters/contrib_adapters.plugin_manifest.json
docs/tutorials/otio-serialized-schema-only-fields.md
docs/tutorials/otio-serialized-schema.md
docs/tutorials/write-a-hookscript.md
docs/tutorials/write-a-media-linker.md
docs/tutorials/write-a-schemadef.md
docs/tutorials/write-an-adapter.md
examples/sample_plugin/otio_counter/__init__.py
examples/sample_plugin/otio_counter/plugin_manifest.json
src/py-opentimelineio/opentimelineio/adapters/adapter.py
src/py-opentimelineio/opentimelineio/adapters/builtin_adapters.plugin_manifest.json
src/py-opentimelineio/opentimelineio/hooks.py
src/py-opentimelineio/opentimelineio/media_linker.py
src/py-opentimelineio/opentimelineio/plugins/python_plugin.py
src/py-opentimelineio/opentimelineio/schema/schemadef.py
tests/baselines/adapter_example.json
tests/baselines/hookscript_example.json
tests/baselines/media_linker_example.json
tests/baselines/plugin_module/otio_jsonplugin/plugin_manifest.json
tests/baselines/plugin_module/otio_mockplugin/unusually_named_plugin_manifest.json
tests/baselines/plugin_module/otio_override_adapter/plugin_manifest.json
tests/baselines/post_write_hookscript_example.json
tests/baselines/schemadef_example.json
tests/test_adapter_plugin.py
tests/test_hooks_plugins.py
tests/test_media_linker.py

When the plugin system was originally designed for the adapter system, the idea was that adapters could be implemented in other languages by sub shelling out.  It was simpler to implement that directly via the `extern_*` pattern seen in the RV and Maya adapters, and now the library is emphasizing native support.  This feature was never implemented, so this PR removes the parameter from the library.
This PR follows #1395 
Closes #728

Remove Plugin schema `execution_scope` parameter

---

.github/workflows/python-package.yml
.gitignore
Makefile
setup.py
src/py-opentimelineio/opentimelineio-bindings/otio_anyDictionary.h
src/py-opentimelineio/opentimelineio-bindings/otio_anyVector.h
src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_tests.cpp
src/py-opentimelineio/opentimelineio/core/_core_utils.py
tests/test_core_utils.py
tests/test_opentime.py
tests/test_serializable_collection.py

This PR adds test coverage for the AnyVector and AnyDictionary python bindings and the `opentimelineio.core._core_utils` module.
It supersedes https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1433.
I also change the builds a little bit so that the coverage is measured in debug mode to improve the accuracy of the C++ code coverage when running the python tests and I also added `--rc lcov_branch_coverage=1` to the `lcov` commands.

Improve test coverage

---

README.md

PyPI ("pie-pee-eye") is the **Py**thon **P**ackage **I**ndex; PyPy ("pie-pie") is an alternative Python implementation. Much digital ink has been spilled over the pronunciation differences alone. (It even has [a dedicated FAQ entry](https://pypi.org/help/#pronunciation) at PyPI.)
I hope it's fine that I did not create an issue for this for the sole purpose of linking it to this PR for auto-closing.
(There are, of course, no tests covering this change, and it will cause no change to the library's behavior.)

README: Fix typo (pypy->pypi)

---

src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp

Yet another type improvement. This time, I'm changing the `name` parameters to be explicit about which types they accept. They accept either None or a string.
Note that this has a side effect. Before, the `name` parameters would accept anything (because of `py::object`), which means that passing a dict would produce `"{}"` for example. I think it's fine if we stop supporting this as it was probably not intentional in the first place.
Question for the TSC: Some constructors use `std::string` for the `name` parameter while some others accept `None` or string. Should we simply just remove support for None? That would simplify things and also make it consistent across constructors.

Replace py::object type by optional<std::string> for name parameters

---

docs/Makefile
docs/tutorials/architecture.md
docs/tutorials/otio-env-variables.md
docs/tutorials/versioning-schemas.md
docs/tutorials/write-a-hookscript.md
docs/tutorials/write-a-media-linker.md
docs/tutorials/write-a-schemadef.md
docs/tutorials/write-an-adapter.md
src/py-opentimelineio/opentimelineio/plugins/manifest.py

Simple PR that makes use of glossaries to define/document environment variables. This allows to reference environment variables from other places in the docs.
See https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-glossary.
The rendered docs can be seen at https://opentimelineio--1442.org.readthedocs.build/en/1442 and an example of how a reference looks like can be seen at https://opentimelineio--1442.org.readthedocs.build/en/1442/tutorials/write-an-adapter.html#custom-adapters.

Use glossary terms for environment variables references in the docs

---

src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py
tests/test_fcp7_xml_adapter.py

Fixes #1410 
This PR removes the hardcoded -1 when serializing markers with duration to FCP XML. Now the out value for markers will be `marked_range.start_time.value + marked_range.duration.value`.
I modified the existing test `test_fcp7_xml_adapter.test_roundtrip_mem2disk2mem`, adding both timeline and clip markers that have durations.

fcp_xml: serialize marker out value instead of -1

---

src/py-opentimelineio/opentimelineio/core/_core_utils.py

A while ago, I found out that the `__iter__` methods defined in our bindings were being overridden in `_core_utils.py`. This PR fixes that by making sure we don't override methods that already exist.
For example, https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/0763bf6e2d34523bf26938c14cfb2730082cff45/src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp#L445 was completely overridden before.
Note that I changed this only in the `_add_mutable_sequence_methods` function. `_add_mutable_mapping_methods` is slightly different in that `AnyDictionary` actually has an `__eq__` method built-in and it needs to be overridden with `__eq__` from `collections.abc`.

Don't override __iter__ methods

---

src/py-opentimelineio/bindings-common/casters.h
src/py-opentimelineio/opentime-bindings/opentime_rationalTime.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_utils.h

A couple of months ago, I noticed that the `drop_frame` parameter of the `RationalTime.to_timecode` method was using `py::object` as its type. This is confusing for the user.
With the change, running `help(opentimelineio.opentime.RationalTime.to_timecode)` returns:
```
to_timecode(...)
to_timecode(*args, **kwargs)
Overloaded function.
1. to_timecode(self: opentimelineio._opentime.RationalTime, rate: float, drop_frame: Optional[bool]) -> str
```
And it still works as before:
```python
>>> opentimelineio.opentime.RationalTime(30 * 59 + 30).to_timecode(29.97, 0)
'00:29:58:06'
>>> opentimelineio.opentime.RationalTime(30 * 59 + 30).to_timecode(29.97, False)
'00:29:58:06'
>>> opentimelineio.opentime.RationalTime(30 * 59 + 30).to_timecode(29.97, 1)
'00:30:00;00'
>>> …
```

Improve typing of the drop_frame parameter on the RationalTime.to_timecode method

---

docs/tutorials/otio-serialized-schema.md
src/py-opentimelineio/opentimelineio-bindings/otio_bindings.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_utils.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_utils.h
src/py-opentimelineio/opentimelineio/core/__init__.py
src/py-opentimelineio/opentimelineio/core/_core_utils.py

Continuation of the work I've been doing to improve the parameter types in our bindings.
In this PR, I'm changing the types of the `children`, `tracks`, `effects` and `markers` parameters. A nice side effect is that we no more need the Python > C++ > Python > C++ > Python dance to convert the inputs from a `py::object` and `AnyVector`s.
Previously, there was an hand-coded bridging to `AnyVector` while now it's using facilities in pybind11 to accomplish the same thing. Part of the reason that's possible, is that `py::object` has been replaced in the interfaces with explicit types that pybind11 knows how to deal with.
Here is an example of why it's important to expose the correct types in constructors (and functions/methods):
The previous behavior was something …

Improve types of childen, tracks, effects and markers parameters in function signatures

---

src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp
src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py

Remove support for passing a None value as the name argument to Marker, Track, Stack and MissingReference constructors
Follow up to https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1446.
As discussed in the last TSC meeting, it has been agreed that we shuld keep the class constructors consistent, which mean that we should drop the ability to pass None values for the name argument of the `Marker`, `Track`, `Stack` and `MissingReference` class constructors.
Passing None is bad in this case because it's inconsistent with the other constructors, which can be seen as not user friendly.
The `name` parameter is always defined as a kwarg with a default value of `''` (empty string). This means that it's still possible to ignore the name parameter entirely when instantiating a …

[Breaking change] Remove support for passing a None value as the name argument

---

.gitignore
MANIFEST.in
docs/tutorials/quickstart.md
setup.py

Fixes #1286.
`seetuptools` added back [editable installs](https://setuptools.pypa.io/en/latest/userguide/development_mode.html) not too long ago and it now supports extensions!
This PR adds support for installing OTIO in editable mode, using `pip install -e .`.
Note that due to the nature of OTIO, the binaries are not editable. There is not much we can do in regard to that since every time the C++ code changed, we need to re-compile the extension. But at least the Python files are editable.

Add support for editable installs

---

.github/workflows/python-package.yml
README.md
setup.py

Python 3.11 was release on Oct. 24, 2022. This PR adds 3.11 to the CI matrix so that we can make sure everything is working as expected even if we don't publish wheels yet.
Note that in order to get 3.11 wheels, I had to update the manylinux docker images to use `manylinux2014`. `manylinux2010` was a CentOS 6 based imaged while 2014 is a CentOS 7 based image. Because 2014 uses glibc 2.17, we are fully compatible with the vfx platform years we support. Also, 2014 uses GCC 10 (10.2.1 to be precised).

Add Python 3.11 to CI matrix

---

docs/tutorials/otio-env-variables.md
examples/sample_plugin/otio_counter/__init__.py
setup.py
src/py-opentimelineio/opentimelineio/plugins/manifest.py
tests/baselines/plugin_module/otio_mockplugin/__init__.py
tests/test_plugin_detection.py

Fixes #1426
As requested in the issue, this replaces `pkg_resources` with `importlib` for plugin detection.
Quick and dirty benchmarks show an improvement in average runtime when accessing plugins:  
The `OTIO_DISABLE_PKG_RESOURCE_PLUGINS` env var and its corresponding test have been removed as they're no longer needed.
Less than ideal, `importlib.metadata` has been in flux since `3.7` so there's some code in here to work with old and new and to avoid a deprecation warning.
Existing tests in `test_plugin_detection` continue to provide coverage.

Switch to using `importlib` from `pkg_resources`

---

.github/workflows/docs.yml
.github/workflows/python-package.yml
tests/baselines/plugin_module/otio_override_adapter/plugin_manifest.json
tests/test_plugin_detection.py

This is part of the #1386 issue, preparing for extraction of cmx_3600 adapter
Replaced "cmx_3600" with "otio_json" in **tests/baselines/plugin_module/otio_override_adapter/plugin_manifest.json** to prevent failing tests when we extract the adapter
Signed-off-by: apetrynet <flehnerheener@gmail.com>

Prepare baseline plugin_manifest.json for removal of the cmx_3600 adapter

---

src/opentimelineio/composable.cpp
src/opentimelineio/item.h
src/opentimelineio/track.cpp
src/opentimelineio/transition.h

Fixes #1513
I noticed a helper function ```_safe_duration()``` that was  dynamically casting a ```Composable``` just to call the function ```duration()```. This isn't necessary since ```duration()``` is a virtual function of ```Composable```. The function ```_safe_duration()``` could be removed and replaced with calls to ```duration()```.

Use duration() as a virtual function

---

CONTRIBUTING.md
GOVERNANCE.md

This PR adds 2 new TSC members and 3 new Committers to OpenTimelineIO. Welcome @jhodges10, @rogernelson, @apetrynet, @darbyjohnston, and @JeanChristopheMorinPerso !

Added new TSC members and new Committers

---

README.md

This PR fixes the sample code in the main README.md to use the updated `find_clips()` method instead of `clip_if()`

Replaced clip_if() with find_clips() in sample code in README.md

---

src/opentimelineio/clip.h
src/opentimelineio/composable.h
src/opentimelineio/composition.h
src/opentimelineio/effect.h
src/opentimelineio/externalReference.h
src/opentimelineio/freezeFrame.h
src/opentimelineio/gap.h
src/opentimelineio/generatorReference.h
src/opentimelineio/imageSequenceReference.h
src/opentimelineio/item.h
src/opentimelineio/linearTimeWarp.h
src/opentimelineio/marker.h
src/opentimelineio/mediaReference.h
src/opentimelineio/missingReference.h
src/opentimelineio/serializableCollection.h
src/opentimelineio/serializableObject.h
src/opentimelineio/serializableObjectWithMetadata.h
src/opentimelineio/stack.h
src/opentimelineio/timeEffect.h
src/opentimelineio/timeline.h
src/opentimelineio/track.h
src/opentimelineio/transition.h
src/opentimelineio/unknownSchema.h

Signed-off-by: Darby Johnston <darbyjohnston@yahoo.com>
Fixes #1542
In C++11 the "override" keyword was added which checks at compile time whether a virtual function has been properly overridden. This can catch bugs from typos in derived classes and ensures that base class destructors are marked virtual. Some interesting discussion here, especially on whether destructors should use "override":
https://github.com/isocpp/CppCoreGuidelines/issues/721
Some compilers (e.g., the latest Xcode) now emit warnings for this:
```
/Users/darby/Dev/otio/OpenTimelineIO/src/opentimelineio/item.h:36:18: warning: 'visible' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
virtual bool visible() const;
```
This PR changes:
* Use the "override" keyword on all …

Use the C++ override keyword

---

src/py-opentimelineio/opentimelineio/console/otiotool.py

This PR adds a `--downgrade` option to `otiotool` to make it easy to write out an older OTIO schema.
From the usage statement:
```
--downgrade FAMILY:VERSION
Downgrade OTIO schema. Only relevant when --output is used to output an OTIO file. FAMILY:VERSION specifies which
schema family and version to use. If FAMILY: is omitted, the default OTIO_CORE: is used. For example `--downgrade
OTIO_CORE:0.14.0` is equivalent to `--downgrade 0.14.0`. See the OpenTimelineIO documentation for
OTIO_DEFAULT_TARGET_VERSION_FAMILY_LABEL for details.
```
Example:
```
otiotool -i new_file.otio --downgrade 0.14.0 -o old_file.otio
```
It uses the downgrade mechanism [documented here](https://opentimelineio.readthedocs.io/en/latest/tutorials/versioning-schemas.html#downgrading-at-runtime).

Added --downgrade option to otiotool.

---

src/py-opentimelineio/opentimelineio/core/_core_utils.py

Fixes #1548
Embed-able Python distributions (at least python 3.7 and 3.9) ship with only byte-code compiled versions of their
built-in modules. As a result, the docstrings of classes, methods will not be set (ie. \_\_doc\_\_ will be set to None)
git commit  https://github.com/AcademySoftwareFoundation/OpenTimelineIO/commit/d48163e464cd37ae272d98ef5dca0c804f840475 introduced a change to exclude external functions (namely from `collections_abc`) from the OTIO sphinx documentation by appending a tag to the \_\_doc\_\_ string. However the code assumes that \_\_doc\_\_ is always set to a string.
On embedded python this will result in a crash with the following error:
``` …
```

Fix exception when __doc__ is None with portable Python

---

src/opentimelineio/serialization.cpp
tests/CMakeLists.txt
tests/test_serialization.cpp

When we use `opentimelineio.serialize_json_to_string` and we set `indent` to 0, it outputs using multiple lines with no indentation instead of outputting a compact, single line string:
```python
>>> opentimelineio.core.serialize_json_to_string(so, indent=0)
{
"OTIO_SCHEMA": "SerializableObjectWithMetadata.1",
"metadata": {
"a": "asd",
"b": "b"
},
"name": "sowithmet"
}
```
With this change, it will output a single line:
```python
>>> opentimelineio.core.serialize_json_to_string(so, indent=0)
{"OTIO_SCHEMA":"SerializableObjectWithMetadata.1","metadata":{"a":"asd","b":"b"},"name":"sowithmet"}
```
A compact string can be useful in unit tests.
Note that I'm still learning C++. The method I used adds some code duplication which I initially tried to avoid but couldn't find a way to avoid it. For …

Make serialize_json_to_string output compact when indent is less than 1

---

src/opentime/rationalTime.h

When compiling with GCC 13, we get errors like this:
```
In file included from /home/jcmorin/jcmenv/aswf/OpenTimelineIO/src/opentime/rationalTime.cpp:4:
/home/jcmorin/jcmenv/aswf/OpenTimelineIO/src/opentime/rationalTime.h: In function ‘constexpr double opentime::v1_0::fabs(double)’:
/home/jcmorin/jcmenv/aswf/OpenTimelineIO/src/opentime/rationalTime.h:27:9: error: ‘uint64_t’ does not name a type
27 |         uint64_t i;
|         ^~~~~~~~
/home/jcmorin/jcmenv/aswf/OpenTimelineIO/src/opentime/rationalTime.h:10:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
9 | #include <limits>
+++ |+#include <cstdint>
10 | #include <string>
/home/jcmorin/jcmenv/aswf/OpenTimelineIO/src/opentime/rationalTime.h:29:10: error: ‘union …
```

Support compiling with GCC 13

---

docs/tutorials/otio-filebundles.md

Fixes #1604.
The rendered version can be seen at https://opentimelineio--1606.org.readthedocs.build/en/1606/tutorials/otio-filebundles.html#structure.

Fix rendering of otioz file bundle structure in the docs

---

setup.py

I noticed that our package in PyPI was still advertising the old license (Modified Apache 2.0). So this PR fixes that to make sure. Our next release will now correctly show Apache 2.0.

Adjust license for package uploaded to PyPI

---

src/opentimelineio/clip.cpp
src/opentimelineio/clip.h
src/opentimelineio/composable.cpp
src/opentimelineio/composable.h
src/opentimelineio/deserialization.cpp
src/opentimelineio/externalReference.cpp
src/opentimelineio/externalReference.h
src/opentimelineio/generatorReference.cpp
src/opentimelineio/generatorReference.h
src/opentimelineio/imageSequenceReference.cpp
src/opentimelineio/imageSequenceReference.h
src/opentimelineio/mediaReference.cpp
src/opentimelineio/mediaReference.h
src/opentimelineio/missingReference.cpp
src/opentimelineio/missingReference.h
src/opentimelineio/safely_typed_any.cpp
src/opentimelineio/safely_typed_any.h
src/opentimelineio/serializableObject.h
src/opentimelineio/serialization.cpp
src/opentimelineio/stack.cpp
src/opentimelineio/stack.h
src/opentimelineio/timeline.h
src/opentimelineio/track.cpp
src/opentimelineio/track.h
src/py-opentimelineio/opentimelineio-bindings/otio_imath.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp

Fixes #1499
Use the Imath namespace preprocessor macro `IMATH_NAMESPACE` in place of `Imath`. This allows an external-use Imath with a custom namespace to be used. This PR addresses at least one of the issues from bug report #1499.
Changed all the source code references of `Imath::` with `IMATH_NAMESPACE::`.

Use IMATH_NAMESPACE in place of Imath

---

.github/workflows/python-package.yml
src/opentime/CMakeLists.txt
src/opentime/OpenTimeConfig.cmake.in
src/opentimelineio/CMakeLists.txt
src/opentimelineio/OpenTimelineIOConfig.cmake.in
tests/consumer/CMakeLists.txt
tests/consumer/opentime/CMakeLists.txt
tests/consumer/opentimeline/CMakeLists.txt

Proposed fixes for https://github.com/AcademySoftwareFoundation/OpenTimelineIO/issues/1192
In terms of CMake target resolution in link steps, just finding OpenTimelineIO was insufficient, as it depends on OpenTime, so consumers needed to know this detail. It's preferrable that consumers just find packages they are interested in, without knowledge of implementation details of build dependencies.
This change moves to using a canonical form of CMake config files, whereby the `*Config.cmake` is generated from a template allowing dependencies to be found, while the CMake generation of import targets is renamed to a `*Targets.cmake` file. The `*Config.cmake` file includes the `*Target.cmake` file.
See https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#cre …

CMake config file improvements to find dependencies automatically for consumers

---

docs/tutorials/versioning-schemas.md

The documentation left out a required argument for using the downgrading system from python in one of its examples. Also clarifies how to get core schemas from python.

fix a bug in the docs for using schema downgrading

---

src/py-opentimelineio/opentimelineio/console/otiotool.py

This PR adds a new `--remove-metadata-key` feature to `otiotool`. If specified, this option looks for the given metadata key(s) on all objects in the OTIO and removes it when found. This could be used to remove private, sensitive, or extraneous metadata from an OTIO.
```
--remove-metadata-key KEY(s) [KEY(s) ...]
Remove one or more metadata keys from all objects.
```
This PR also improves the `otiotool` usage docs, adding some examples, clarifying some arguments, and making the short summary more readable by using the `--long-options` instead of single-letter options.
```
usage: otiotool [-h] [--input PATHs) [PATH(s) ...]] [--video-only] [--audio-only] [--only-tracks-with-name NAME(s) [NAME(s) ...]]
[--only-tracks-with-index INDEX(es) [INDEX(es) ...]] [--only-clips-with-name NAME(s) …
```

Added otiotool --remove-metadata-key option

---

src/py-opentimelineio/bindings-common/casters.h

When building with C++17 turned ON, our `optional` and `any` libraries, `nonstd::optional` and `nonstd::any`, are replaced with the ones present in `std` in C++17 on.  Because Pybind11 already defines casters for the `std::optional`, this causes a build error, duplicate definition, with the definition found in casters.h.  This PR guards the definition in casters.h and adds to the comment describing why its guarded and when casters.h can be removed.

Add C++17 guard to casters.h

---

src/py-opentimelineio/opentimelineio/console/autogen_plugin_documentation.py

Fixes #1643
This change cleans up the code a bit and makes sure it ignores `hooks` plugin types, as they are not getting the same output by `plugin_info_map()` needed for type formatting.
`test_plugin_documentation (test_serialized_schema.PluginDocumentationTester)`

`extract_adapters`: plugin docs generation fails when hook is present

---

src/py-opentimelineio/opentimelineio/url_utils.py
tests/test_url_conversions.py

`filepath_from_url` works for encoded URLs but not for URLs that are not encoded. I encountered this when working with URLs from both `.xml` and `.aaf` files. 
The `.xml` file came from Premiere and encoded the URL while the `.aaf` came from Avid and the URL was not encoded.
Examples:
- `"file://localhost/S%3a/path/file.ext"` -> `"S:/path/file.ext"`
- `"file://S:/path/file.ext"` -> `"/path/file.ext"`
My PR updates the code to return the same result with both of the example URLs:
- `"file://localhost/S%3a/path/file.ext"` -> `"S:/path/file.ext"`
- `"file://S:/path/file.ext"` -> `"S:/path/file.ext"`
I tested and dev-ed this on Windows with OTIO `0.15.0` and `0.16.0.dev1`.

Adds support to `filepath_from_url` to support non-encoded URLs

---

src/py-opentimelineio/opentimelineio/console/otioconvert.py
src/py-opentimelineio/opentimelineio/console/otiopluginfo.py
src/py-opentimelineio/opentimelineio/plugins/manifest.py

`pkg_resources` is now deprecated. This PR removes references to that module.
Refactored `plugin.manifest` module to factor the pip installed package discovery into a separate function. Made `otiopluginfo` and `otioconvert` use that function rather than doing their own plugin discovery.
I did not add new tests, but I validated the output of `otiopluginfo --version` and `otioconvert --version` to validate they're nearly identical. The only difference is that the string `Plugins from pkg_resources:` is now `Plugins from installed packages:`.

Replaced usages of deprecated pkg_resources module

---

src/opentime/rationalTime.h
src/opentime/timeRange.h
src/py-opentimelineio/opentime-bindings/opentime_rationalTime.cpp
tests/test_opentime.cpp
tests/test_opentime.py

Fixes #1622
This PR adds a few utility functions to RationalTime for comparison and rounding:
* A function that compares whether two RationalTimes have the same value and rate. This is different from the "==" operator which scales the time before comparison (e.g., otime::RationalTime(30.2) == otime::RationalTime(60.4, 2.0)).
* Rounding functions that return the floor(), ceil(), and round() of a RationalTime.
If these seem useful I can also add Python bindings for them.

Add utility functions for comparison and rounding

---

GOVERNANCE.md

In line with the TSC vote on December 7 2023, updated the Chair in `GOVERNANCE.md` from Josh Minor to Eric Reinecke.

Updated TSC chair in GOVERNANCE.md

---

docs/tutorials/otio-timeline-structure.md

This PR adds notes on rendering since rendering behavior is unclear from the specification itself.

add rendering notes

---

.github/workflows/python-package.yml
src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py
src/py-opentimelineio/opentimelineio/plugins/python_plugin.py
src/py-opentimelineio/opentimelineio/url_utils.py

https://github.com/AcademySoftwareFoundation/OpenTimelineIO/issues/1668
The imp module in Python is deprecated since Python 3.4 and is removed in Python 3.12. So the package cannot be imported in Python 3.12 because the imp module doesn't exist anymore. See my issue.
By reading the docs it have to be changed by importlib. So I have made these changes and this works for importing adapters for example :) 
Some documentation :
https://docs.python.org/3.12/whatsnew/3.12.html#imp
https://docs.python.org/3.11/library/imp.html
I have added Python 3.12 in the workflow for Python package. 
I use some linter (black) in my vscode so my changes can be more than the real modifications. If you want I can revert these …

Python 3.12 support / imp module deleted

---

.github/workflows/python-package.yml

Windows builds have been failing with the message: `Invalid --only='""', must be a build selector with a known platform`
cibuildwheel version 2.16.5 addresses this.
See pypa/cibuildwheel/issues/1740 for details.

fix: Bumped cibuildwheel action to 2.16.5 to address windows build issues

---

docs/tutorials/otio-serialized-schema-only-fields.md
docs/tutorials/otio-serialized-schema.md
src/opentimelineio/marker.cpp
src/opentimelineio/marker.h
src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp
tests/baselines/empty_marker.json
tests/test_marker.py

Fixes #744
This adds an optional comment field to the Marker object as requested in #744 
Added new tests that specifically test to make sure the comment is being added and serialized/deserialized successfully

Add optional comment field to Marker

---

src/py-opentimelineio/opentimelineio/adapters/__init__.py
tests/test_builtin_adapters.py

Simple little PR: Currently the `read_from_file`, `write_to_file` of `opentimelineio.adapter` do not support `pathlib.Path` objects for their filepath argument. This addresses this.

Added support for pathlib.Path filepath arguments for adapter IO functions

---

src/py-opentimelineio/opentimelineio/adapters/adapter.py

Fixes #1321
As Py2 support is dropped we should be free to commit utf-8 encoding in Python Adapters to handle UTF in input data.

Fix non latin symbols decoding in adapters

---

src/opentimelineio/stackAlgorithm.cpp
tests/CMakeLists.txt
tests/test_stack_algo.cpp

This PR fixes #1430
I added a `_normalize_tracks_lengths` function that adds gap items to the end of tracks that are shorter before the flattening happens.

Normalize track lengths with gaps before flatten stacks

---

src/py-opentimelineio/opentimelineio/url_utils.py
tests/test_url_conversions.py

This PR is a follow up to https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1664 to add support to `filepath_from_url` and tests for UNC paths.

Added support to filepath_from_url for UNC paths and tests for UNC and posix paths

---

setup.py

The `setup.py` build_py action uses the `editable_mode` attribute, however there are some invocation paths where this isn't set.
This adds defaulting behavior to avoid an `AttributeError` in those cases.
I validated this through the various `make`, `pip`, and `python setup.py...` commands.

Fixed AttributeError: editable_mode in setup.py

---

src/opentime/rationalTime.cpp
src/opentime/rationalTime.h
src/py-opentimelineio/opentime-bindings/opentime_rationalTime.cpp
src/py-opentimelineio/opentimelineio/opentime.py

Add implementation of `to_nearest_timecode` which makes approximate conversion of timecode from a rate using the closest valid time code rate.
This is intended to fix various downstream adaptor hiccups where source material might be variable frame rate, or close but not quite an exact SMPTE timecode.
https://github.com/AcademySoftwareFoundation/OpenTimelineIO/issues/830
This PR does not directly fix the FCP_XML adaptor, but rather isolates changes to OTIO core and exposes a `to_nearest_timecode` with the same method signature as `to_timecode`. 
This is intended to act as a entry point for changes to other adaptors if deemed a valid approach
No new tests just yet.

Add implementation of to_nearest_timecode

---

.github/workflows/python-package.yml

Codecov uploader is no longer compatible w/ python 3.7, which was causing action failures against the python 3.7 target.  This switches it to use the 3.10 version of python instead.  It also updates to the v4 codecov uploader.

Update codecov to run on python 3.10 builds

---

.github/workflows/python-package.yml

This PR adds macOS arm64 runners for #1672
The only issue I'm facing is python 3.8 and 3.9 aren't working with the current `setup-python` action.
https://github.com/actions/setup-python/issues/696
Wheels can still be made, python 3.8 and 3.9 are supported with the `cibuildwheel` action. 
python-3.9 is the version of python included on macOS, so its annoying the test aren't running.
As for python-3.7, it was never supported for apple silicon as far as I understand.

Add macos-14 arm64 runners

---

.github/workflows/python-package.yml

Make sure that problems uploading to codecov do not indicate broken PRs.

do not break the build if codecov fails

---

examples/conform.cpp
examples/io_perf_test.cpp

Fixes #1722
A couple fixes for the example code needed by the recent upgrade to C++ 17.

Fix examples for C++ 17

---

CMakeLists.txt

Fixes #1718
Compiling the latest OTIO with C++17 support gives this error on macOS 10.15.7:
```
'any_cast<const opentimelineio::v1_0::AnyVector &>' is unavailable: introduced in macOS 10.14
AnyVector const& av = std::any_cast<AnyVector const&>(source);
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/any:581:12: note:
'any_cast<const opentimelineio::v1_0::AnyVector &>' has been explicitly marked unavailable here
```
Bumping CMAKE_OSX_DEPLOYMENT_TARGET to 10.14 fixes the issue.

Set minimum OS X deployment version to 10.14

---

src/opentime/rationalTime.h
src/opentime/timeRange.h
src/opentime/timeTransform.h

Fixes #1720
Changes:
* Add `constexpr` to more functions in OpenTime
* Remove redundant `inline` on `constexpr` functions
* Move `constexpr` before the return type on functions

constexpr updates

---

contrib/opentimelineio_contrib/adapters/fcpx_xml.py
src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py

During the tests some DeprecationWarnings pop up. I only fix them. 
For example here you see the DeprecationWarnings : https://github.com/AcademySoftwareFoundation/OpenTimelineIO/actions/runs/7483248301/job/20368203066?pr=1669#step:9:18

Remove some DeprecationWarnings

---

src/opentimelineio/stackAlgorithm.cpp

Simple pull request to remove a new warning under GCC 14.
The warning is
```
/home/jcmorin/jcmenv/aswf/OpenTimelineIO/src/opentimelineio/stackAlgorithm.cpp: In function ‘void opentimelineio::v1_0::_normalize_tracks_lengths(std::vector<Track*>&, TrackRetainerVector&, ErrorStatus*)’:
/home/jcmorin/jcmenv/aswf/OpenTimelineIO/src/opentimelineio/stackAlgorithm.cpp:147:23: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<opentimelineio::v1_0::Track*>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
147 |     for (int i = 0; i < tracks.size(); i++)
|                     ~~^~~~~~~~~~~~~~~
```

Fix sign-compare warning when compiling with GCC 14

---

.github/workflows/python-package.yml

Fixes #1757
Added step to force pip update in msys2 based on [these directions](https://github.com/pypa/pip/issues/7783#issuecomment-590870134).

Added fix for pip._vendor.distlib issue on windows msys2

---

src/opentime/rationalTime.h

Fixes #1753
Adds Doxygen comments to the RationalTime class. These comments are based on the Python doc strings with some editing for consistency.
(This PR replaces #1746 which got into some git trouble.)

Add Doxygen comments to RationalTime #2

---

CONTRIBUTING.md

Addresses a TO-DO item from #1386.
Documented the OpenTimelineIO-Plugins versioning strategy in CONTRIBUTING.md

Added notes about versioning OpenTimelineIO-Plugins

---

.github/release-drafter.yml
.github/workflows/docs.yml
.github/workflows/pr-tools.yml
.github/workflows/python-package.yml
.github/workflows/release-preview.yml
.github/workflows/release-publish.yml

Follow-up to -> #1690 
- Update `actions/checkout@v3` -> `actions/checkout@v4`
- Fix path of the `release-branch.sh` script

Resolve CI issues and bump actions/checkout from v3->v4

---

.github/workflows/python-package.yml
Makefile
maintainers/freeze_ci_versions.py

The freeze CI versions script had broken with an update to the GitHub documentation formatting. This update uses a slightly more markdown-aware approach to extract the needed info.
Also addressed minor escaping issue in Makefile I'd discovered while cutting the 0.16.0 release.

Fixed freeze script github yaml parsing and unfroze the ci versions

---

src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp
tests/test_track.py

Fixes #1680
**Summary**
Changes to reference parameter to raise `TypeError` instead of crashing with a segmentation fault. Created `test_append_none` to prevent regression.

#1680 fix segmentation fault when appending None

---

docs/tutorials/otio-filebundles.md
src/py-opentimelineio/opentimelineio/adapters/file_bundle_utils.py
src/py-opentimelineio/opentimelineio/adapters/otiod.py
src/py-opentimelineio/opentimelineio/adapters/otioz.py
src/py-opentimelineio/opentimelineio/url_utils.py

Following conversation with @darbyjohnston, an attempt to clean up and clarify the documentation for the file bundle adpaters.

Second draft of file bundle adapter docs.

---

docs/tutorials/time-ranges.md

Fixes #1347
**Summary**
Extends time range documentation to include tracks, transitions, gaps, stacks, and timelines.

Fix #1347 documentation on time ranges

---

src/py-opentimelineio/opentimelineio/console/otiotool.py

Fixes #1677
**Summary**
Adds `--verify-ranges` option for otiotool's inspection feature, verifies that the clip's source range doesn't start before the available start range or ends beyond it (if the available range exists).

#1677 otiotool verify ranges

---

pyproject.toml

Fixes #1788 
This PR disables x86 builds to help reduce CI time and troubleshooting.
Marking this as WIP to test the changes.

Disable 32-bit Python builds

---

src/opentimelineio/composition.h
src/opentimelineio/stack.cpp
src/opentimelineio/stack.h
tests/test_track.cpp
tests/test_track.py

Fixes #1652
This PR is a replacement for #1755 which has some trouble with the git history.
After some investigation, it looks like the find_children() function was not working with stacks when given a search range. To fix this, an override is added for the function children_in_range() that works with "stacks" of children.

Fix for find_children() with stacks #2

---

.github/workflows/python-package.yml
pyproject.toml

Add support for building wheels for Linux on ARM architecture.
This covers both ARM64 hardware running Linux directly, as well as Docker containers running under other operating systems, such as Docker on MacOS.
Our use case is to speed up installs of the package in Docker running on Apple M1 MacBooks.
See docs https://cibuildwheel.pypa.io/en/stable/faq/#emulation
Note there is a time penalty to building this wheel under emulation.

Add Python build for Linux on ARM architecture

---

src/opentimelineio/clip.cpp
src/opentimelineio/clip.h
src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp
src/py-opentimelineio/opentimelineio/schema/clip.py
tests/test_clip.cpp
tests/test_clip.py

Extend `Clip` to allow effects and markers to be set, matching how `Gap`'s can be initialized.
Added basic C++ and Python tests.

Add effect and marker initialization to Clip

---

src/py-opentimelineio/opentimelineio-bindings/otio_bindings.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_utils.cpp
tests/test_composable.py
tests/test_serializable_object.py

Fixes #1714
Add Imath V2d and Box2d types so they can be added as metadata in AnyDictionary and AnyVector containers.
Add basic tests for V2d and Box2d to serializable object tests. Also, adapt the composable object test, to test metadata serialization.

Add AnyDictionary and AnyVector support for V2d and Box2d

---

.github/workflows/python-package.yml
.readthedocs.yml
CMakeLists.txt
Makefile
src/opentimelineio/typeRegistry.h
tests/test_clip.py

It looks like the gcc version in the CI may have changed which is causing issues with gcov/geninfo:
```
geninfo: ERROR: "/home/runner/work/OpenTimelineIO/OpenTimelineIO/src/deps/rapidjson/include/rapidjson/reader.h":271: mismatched exception tag for id 1, 1: '0' -> '1'
```
This PR fixes the issue by removing rapidjson from the coverage. It also includes other build fixes from this PR:
https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1820

Fix CI issue with gcov

---

docs/tutorials/otio-serialized-schema.md

In #1821 a number of typos were fixed, however this also removed whitespace in `otio-serialized-schema.md` which causes a mismatch with the generator for that file and test failure.
This PR restores the machine-generated version of that file.

Revert whitespace changes to otio-serialized-schema.md

---

.github/workflows/pypi-publish.yml
.github/workflows/python-package.yml

This PR includes the changes from #1827 plus some additional changes to fix the CI:
* Update dawidd6/action-download-artifact to v8
* Update actions/setup-python to v5.4.0
* Use `ubuntu-24.04-arm` for native Linux ARM builds (replacing the QEMU emulator builds)
* Update pypa/cibuildwheel to v2.22.0

Update GH actions to fix CI builds

---

.github/workflows/pypi-publish.yml

As the title says. Backticks are not valid in YAML.

Replace backticks with quotes in pypi-publish GHA workflow

---

CMakeLists.txt
src/opentimelineio/CMakeLists.txt
src/opentimelineio/OpenTimelineIOConfig.cmake.in
src/opentimelineio/composable.h
src/opentimelineio/mediaReference.h
src/opentimelineio/serializableObject.h
src/py-opentimelineio/opentimelineio-bindings/CMakeLists.txt
src/py-opentimelineio/opentimelineio-bindings/otio_bindings.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_imath.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp
src/py-opentimelineio/opentimelineio-bindings/otio_utils.cpp
tests/CMakeLists.txt

As quickly discussed in the Slack channel...
OpenEXR developers [recommend to use full namespace includes](https://github.com/AcademySoftwareFoundation/Imath/issues/136#issuecomment-812671628) like `#include <Imath/ImathBox.h>`, but we still use `#include <ImathBox.h>`.
The support of OpenEXR/Imath 2 blocks changing the includes to full namespace. However Imath 3 has be released 4 years ago and OpenEXR/Imath 2 is no longer on the vfxplatform horizon so it seems appropriated to just remove support for it.

Drop Imath2 support and modernize Imath includes

---

docs/tutorials/write-a-hookscript.md
src/py-opentimelineio/opentimelineio/adapters/adapter.py
src/py-opentimelineio/opentimelineio/console/otiopluginfo.py
tests/baselines/adapter_plugin_manifest.plugin_manifest.json
tests/baselines/custom_adapter_hookscript_example.json
tests/baselines/custom_adapter_hookscript_example.py
tests/baselines/example.py
tests/test_adapter_plugin.py
tests/test_hooks_plugins.py

_Rebased PR #1711_
Required by https://github.com/OpenTimelineIO/otio-aaf-adapter/pull/43
This adds support for attributing custom hooks to adapters and executing them with `hook_function_argument_map` being passed along through the adapter IO functions.
**Describe the reason for the change.**
I added two custom hooks to the OTIO AAF adapter (https://github.com/OpenTimelineIO/otio-aaf-adapter/pull/43), allowing for embedding of media essence into the resulting AAF. This was needed to facilitate just-in-time DNXHR transcoding of the media for the AAF creation and adding a certain level of control and flexibility to the feature. 
These features to the core are required in order to properly pass the hook argument map along to potential custom hooks run by the …

Added support for custom adapter hooks

---

src/opentimelineio/serialization.cpp
tests/test_v2d.py

```Fixes #1855```
This is a bug fix where V2d was getting serialized into two V2ds inside a Box2d.  The problem was that there was no `write_value` function in the serialization for V2d (I guess it was assumed a V2d would always be inside a Box2d).  Box2d has an implicit ctor taking a V2d, which implicitly converted the V2d to a Box2d to match on the Box2d `write_value` method. 
Notes:
`make test` required me to run `make doc-model-update` which added some whitespace changes to otio-serialized-schema.md
`make lint` changed some whitespacing in the v2d test
Two new tests added to `test_v2d.py`
- Check the schema is correct when serializing to json
- Round trip serialization/deserialization ensures we get the original value back

V2d serialization fix

---

CMakeLists.txt
src/deps/CMakeLists.txt
src/opentimelineio/CMakeLists.txt

For (Linux) distro packaging it is common to use system packages instead of submodules and co.
With this option one can ask to use the system rapidjson with CMake flag instead of maintaining custom patches such as https://build.opensuse.org/projects/KDE:Applications/packages/opentimelineio/files/0001-Use-system-rapidjson.patch?expand=1
Note: if `OTIO_FIND_RAPIDJSON` is `ON` but rapidjson is not found cmake fails. This behavior is different to `OTIO_FIND_IMATH` where it will just continue with `src/deps` as a fallback. However I think if the user explicitly request the system package it makes more sense to fail if not found. In my opinion this should be changed for Imath as well, but that is offtopic for this PR

Allow to use rapidjson from the system

---

src/py-opentimelineio/opentimelineio/url_utils.py
tests/test_url_conversions.py

* Fix traceback when using relative paths with one "/" and not two "/" were triggering a traceback - ie "./blah" but not "./blah/blah" in url_utils. 
* url_utils is used by the otioz adapter (Which is where this was originally reported)
Fixes #1817

Fix bug w/ url_utils.filepath_from_url + rel paths with a single "/"

---

doxygen/config/dox_config
src/opentime/errorStatus.h
src/opentime/rationalTime.h
src/opentime/stringPrintf.h
src/opentime/timeRange.h
src/opentime/timeTransform.h

This change completes adding Doxygen style comments to the opentime API. The changes are just comments, there are no functional changes to the API.
Most of the comments were straightforward, but any feedback to help improve them is welcome.
I added a Doxygen group for the TimeRange "relations" and `<pre>` tags to keep the ASCII diagrams intact in the Doxygen HTML.
I also made a couple of tweaks to the Doxygen configuration to remove non-public info and keep the sorting order the same as the header files.

Add Doxygen comments to opentime

---

CMakeLists.txt
src/deps/CMakeLists.txt

It seems to be a relic from Imath2 where it would have made sense as it required a custom find OpenEXR script. However the option is dead (and appears to have ever been) and is not usefull for Imath3 anyways.
As discussed with @meshula on Slack

Drop dead OTIO_IMATH_LIBS cmake option

---

src/opentimelineio/CMakeLists.txt

This change removes an unused path from the C++ installation. Previously the "any" and "optional" headers were installed into `${OTIO_RESOLVED_CXX_INSTALL_DIR}/include/opentimelineio/deps)`, but they were removed with the transition to C++17.
Currently trying to use the OTIO CMake config gives this error:
```
CMake Error in CMakeLists.txt:
Imported target "OTIO::opentimelineio" includes non-existent path
"install/include/opentimelineio/deps"
in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
* The path was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and references files it does not
provide.
```
It looks like the Imath dependency is not installed to `deps`, but …

Remove unused path from the C++ install

---

.github/workflows/python-package.yml
README.md
setup.py
src/py-opentimelineio/opentimelineio/plugins/manifest.py
tests/baselines/plugin_module/otio_mockplugin/__init__.py
tests/test_plugin_detection.py

Fixes #1876 
Fixes #1804 
* Removes VFX Platform 2020 from the badge, adds 2024 and 2025
* stripped out code blocks that indicated they were present for python versions before 3.9.
* Adds notes that Pyhon 3.12 is supported (CI is already running on 3.12, binaries are already built)
As noted in the comments below by @JeanChristopheMorinPerso, this PR doesn't fully cover #1094, it doesn't add any of the VFX platform container related testing stuff.

Remove vfx platform 2020 support from README.md, add 2024 and 2025, note that 3.12 is also supported

---

.github/workflows/python-package.yml

The CI jobs have been failing with this error:
```
Invalid workflow file
The workflow is not valid. .github/workflows/python-package.yml (Line: 172, Col: 17): Unexpected value ''
```
Which I think is coming from the `exclude:` line being empty.

Workflow fix, exclude cannot be empty

---

docs/tutorials/otio-serialized-schema-only-fields.md
docs/tutorials/otio-serialized-schema.md
src/opentimelineio/deserialization.cpp
src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py
src/py-opentimelineio/opentimelineio/core/_core_utils.py
tests/test_json_backend.py

Fixes #1614
Fixes color deserialization so it works correctly. Add to documentation schema generator as well.
Adds serialization test for coverage.

Fix color deserialization, add schema

---

src/py-opentimelineio/opentimelineio/console/otiotool.py
tests/sample_data/effects.otio
tests/test_console.py

Sometimes you have effects in your timeline that you want to remove. This PR adds a `--remove-effects` option to otiotool to make that easy and convenient.
Example:
```
otiotool -i effects.otio --remove-effects -o no-effects.otio
```

Added --remove-effects feature to otiotool.

---

docs/index.rst
docs/tutorials/otiotool.md
src/py-opentimelineio/opentimelineio/console/otiotool.py

The `otiotool` command line utility has no documentation aside from it's built-in usage statement. This PR adds a documentation page with detailed examples and explanations. This PR also makes a minor improvement to the otiotool command line argument validation & usage statement.

otiotool docs
